# GitGuardian configuration file
# This file configures GitGuardian to handle false positives and known secrets
# Updated: 2025-12-02 - All example keys from PR are allowlisted below

# Paths to skip entirely
paths-ignore:
  - "node_modules/**"
  - ".git/**"
  - ".pytest_cache/**"
  - "__pycache__/**"
  - ".venv/**"
  - "venv/**"
  - "dist/**"
  - "build/**"
  # Specific files with example keys (not broad patterns)
  - "scripts/validation/validate_openrouter_auto_access.py"
  - "tests/integration/test_openrouter_auto_live.py"
  - "test_openrouter_auto_curl.sh"
  - "docs/deployment/VERCEL_DEPLOYMENT.md"
  - "docs/OPENROUTER_AUTH_FIX.md"

# Explicitly allowlist secrets that were exposed in git history but are now removed
# These test keys have been rotated and should not be used
allowlist:
  # Test API key that was removed (commit 848c2f9b)
  - "gw_live_01eQv2HGWkjo0ApxoC4-G3yaOv6ilbzJwL9t6QpjQ5c"
  # Supabase test key that was removed (commit 848c2f9b)
  - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlubGVyb2VoeXJtYWFma2dqZ21yIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTY4Nzc3OSwiZXhwIjoyMDc1MjYzNzc5fQ.kIehmSJC9EX86rkhCbhzX6ZHiTfQO7k6ZM2wU4e6JNs"
  # First exposed test key from performance tests
  - "gw_live_keYT21TicJZzxObd8-6LJukxOg5p0CLo_3Yki83w3pU"
  # OpenRouter example key in VERCEL_DEPLOYMENT.md (documentation only - replaced)
  - "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"
  # Admin API key example in VERCEL_DEPLOYMENT.md (documentation only - replaced)
  - "gjrxRyE-JjXwj8vR2HRTCwJ33fc5FmoDbJfRD_52UhQ"
  # Resend API key example in VERCEL_DEPLOYMENT.md (documentation only - replaced)
  - "re_8nSfCD6U_B5AqufQerhUJMi2ckUtXRefs"

# Stricter scanning for specific paths
paths-strict:
  - "src/**"
  - "api/**"
