# GitGuardian Configuration
# This file tells GitGuardian which files/patterns to ignore during security scans

version: 2

# Paths to ignore - these files contain only test/mock credentials
paths-ignore:
  - .env.test
  - tests/conftest.py
  - "**/*test*.env"
  - "**/*.test.env"
  - "**/mock*.env"

# Patterns to ignore - specific patterns that are known to be safe
matches-ignore:
  # Mock/fake test credentials
  - name: Mock Test Credentials
    match: mock-test-.*-fake-.*-000
  - name: Test Environment Markers
    match: (FAKE|MOCK|TEST).*for testing only
