version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gatewayz-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gatewayz
      POSTGRES_PASSWORD: gatewayz_dev_password
      POSTGRES_DB: gatewayz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gatewayz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gatewayz-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: gatewayz-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - gatewayz-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  gatewayz-network:
    driver: bridge