site_name: AI Gateway Documentation
docs_dir: docs
nav:
  - Home: index.md
  - Introduction:
      - What is the AI Gateway?: introduction/what-is-gateway.md
      - Key Features: introduction/key-features.md
      - When to Use the AI Gateway: introduction/use-cases.md
  - Getting Started:
      - Setup Guide: setup.md
      - Environment Configuration: environment.md
      - Architecture: architecture.md
  - API Reference: api.md
  - Deployment: deployment.md
  - Operations: operations.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
