#!/usr/bin/env python3
"""
Extract model pricing warnings from Railway deployment logs.
This script retrieves the latest deployment logs and extracts all models
that are using default pricing due to missing catalog entries.
"""

import os
import sys
from collections import defaultdict
import re
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))


def parse_model_warning_line(line):
    """
    Parse a model warning line from logs.

    Expected format:
    ⚠️ Model provider/model-name (normalized: provider/normalized-name) not found in catalog, using default pricing

    Returns:
        dict: Model info with original, normalized, and provider keys, or None if parsing fails
    """
    pattern = r'⚠️\s+Model\s+([^\s]+)\s+\(normalized:\s+([^)]+)\)\s+not found in catalog'
    match = re.search(pattern, line)

    if match:
        original = match.group(1)
        normalized = match.group(2)

        # Extract provider from original model ID
        provider = original.split('/')[0] if '/' in original else 'unknown'

        return {
            'original': original,
            'normalized': normalized,
            'provider': provider,
            'pricing': 'default'
        }

    return None


def extract_warnings_from_logs(log_text):
    """
    Extract all model pricing warnings from log text.

    Args:
        log_text (str): Raw log text from Railway deployment

    Returns:
        dict: Dictionary mapping providers to lists of model warnings
    """
    warnings = defaultdict(list)

    for line in log_text.split('\n'):
        if 'not found in catalog' in line and 'Model' in line:
            model_info = parse_model_warning_line(line)
            if model_info:
                warnings[model_info['provider']].append(model_info)

    # Remove duplicates
    for provider in warnings:
        seen = set()
        unique_warnings = []
        for warning in warnings[provider]:
            key = (warning['original'], warning['normalized'])
            if key not in seen:
                seen.add(key)
                unique_warnings.append(warning)
        warnings[provider] = unique_warnings

    return dict(warnings)


def format_markdown_report(warnings):
    """
    Format warnings as a markdown report.

    Args:
        warnings (dict): Dictionary of warnings by provider

    Returns:
        str: Formatted markdown report
    """
    if not warnings:
        return """# Model Pricing Warnings Report

**Generated**: {timestamp}

## Summary

✅ No models with missing pricing detected in deployment logs.

All models in the catalog have proper pricing configuration.
""".format(timestamp=datetime.now().isoformat())

    total_models = sum(len(models) for models in warnings.values())

    report = f"""# Model Pricing Warnings Report

**Generated**: {datetime.now().isoformat()}

## Summary

**Providers with Missing Pricing**: {len(warnings)}
**Total Models Using Default Pricing**: {total_models}

### Impact Assessment

These warnings indicate models that exist in provider catalogs but lack specific pricing
configuration in the Gatewayz pricing database. The system automatically uses default
pricing for these models to maintain service continuity.

**Status**: ⚠️ Non-critical - Service continues with default pricing fallback

---

## Models by Provider

"""

    for provider in sorted(warnings.keys()):
        models = warnings[provider]
        report += f"\n### {provider.upper()}\n\n"
        report += f"**Models with Default Pricing**: {len(models)}\n\n"
        report += "| Original Model ID | Normalized Model ID | Pricing Status |\n"
        report += "|-------------------|---------------------|----------------|\n"

        for model in sorted(models, key=lambda x: x['original']):
            report += f"| `{model['original']}` | `{model['normalized']}` | **Default** |\n"

        report += "\n"

    report += """---

## Recommended Actions

1. **Review New Models**: Verify these are intentional new model additions
2. **Add Pricing**: Update the pricing database with actual provider pricing for these models
3. **Verify Mappings**: Ensure model ID normalizations are correct (original → normalized)
4. **Document Defaults**: If default pricing is acceptable, document this in pricing policy

## Technical Details

- **Detection Method**: Parsed from Railway deployment logs during model catalog sync
- **Default Pricing Behavior**: System uses fallback pricing configuration when model-specific pricing is unavailable
- **Service Impact**: None - all requests continue to function normally

---

*Generated by `extract_model_pricing_warnings.py`*
"""

    return report


def main():
    """Main function to extract and report model pricing warnings."""

    print("🔍 Model Pricing Warnings Extraction Script")
    print("=" * 50)
    print()

    # For now, use the sample we extracted from the truncated logs
    # In production, this would fetch from Railway API

    sample_log_data = """
2026-01-15 15:16:19    ⚠️ Model alibaba/qwen-3-14b (normalized: alibaba/qwen-3-14b) not found in catalog, using default pricing
2026-01-15 15:16:19    ⚠️ Model google/gemini-2.0-flash (normalized: google/gemini-2.0-flash) not found in catalog, using default pricing
2026-01-15 15:16:19    ⚠️ Model deepseek/deepseek-chat (normalized: deepseek/deepseek-chat) not found in catalog, using default pricing
2026-01-15 15:16:19    ⚠️ Model mistral/mistral-large (normalized: mistral/mistral-large) not found in catalog, using default pricing
2026-01-15 15:16:19    ⚠️ Model meta/llama-3-8b-instruct (normalized: meta-llama/llama-3-8b-instruct) not found in catalog, using default pricing
2026-01-15 15:16:19    ⚠️ Model bfl/flux-1-1-pro (normalized: black-forest-labs/flux-1.1-pro) not found in catalog, using default pricing
2026-01-15 15:16:19    ⚠️ Model bytedance/sdxl-lightning-4step (normalized: bytedance/sdxl-lightning-4step) not found in catalog, using default pricing
2026-01-15 15:16:19    ⚠️ Model cohere/command-r-plus (normalized: cohere/command-r-plus) not found in catalog, using default pricing
    """

    print("📋 Parsing deployment logs...")
    warnings = extract_warnings_from_logs(sample_log_data)

    if warnings:
        print(f"✅ Found {sum(len(m) for m in warnings.values())} models with pricing warnings")
        print(f"📊 Across {len(warnings)} providers")
    else:
        print("✅ No pricing warnings found")

    print()
    print("📝 Generating report...")
    report = format_markdown_report(warnings)

    # Save report
    output_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'docs', 'fixes')
    os.makedirs(output_dir, exist_ok=True)

    output_file = os.path.join(output_dir, f'MODEL_PRICING_WARNINGS_{datetime.now().strftime("%Y-%m-%d")}.md')

    with open(output_file, 'w') as f:
        f.write(report)

    print(f"✅ Report saved to: {output_file}")
    print()
    print("=" * 50)
    print(report)
    print("=" * 50)

    return 0


if __name__ == '__main__':
    sys.exit(main())
