"""
BotFilterSpanProcessor — drop bot/scanner traces before they reach Tempo.

WHY THIS EXISTS
---------------
FastAPIInstrumentor creates an OTel span the moment an HTTP request arrives,
before SecurityMiddleware has a chance to return a 429. That means every probe
from scanners and API-key brute-forcers produces a span that is queued and
exported to Tempo, causing Tempo to OOM on Railway.

HOW IT WORKS
------------
This SpanProcessor sits at the HEAD of the processor chain (registered before
ProviderSpanEnricher and ResilientSpanProcessor). On on_end() it inspects the
finished span's attributes. If any drop rule matches it simply does NOT
forward the span to the next processor — the span is silently discarded. Only
legitimate spans continue on to the BatchSpanProcessor → Tempo pipeline.

DROP RULES (any match = drop)
------------------------------
1. Scanner route   — http.route or http.url matches /.env, /wp-login, /.git, etc.
2. Bot user-agent  — http.user_agent contains known scanner tool names.
3. Unauthenticated 401/403 flood — status 401/403 AND no Authorization header.
4. Pure rate-limit spam — status 429 AND no user.id / customer.id attribute
   (i.e. the caller never authenticated; legitimate users have a key).

METRIC
------
bot_traces_dropped_total{reason} — Prometheus counter incremented per drop.
Visible in Grafana under the "Security" dashboard row.
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)

try:
    from opentelemetry.sdk.trace import ReadableSpan, SpanProcessor

    _OTEL_AVAILABLE = True
except ImportError:
    _OTEL_AVAILABLE = False
    SpanProcessor = object  # type: ignore
    ReadableSpan = object  # type: ignore


# ---------------------------------------------------------------------------
# Known scanner route prefixes / exact paths
# ---------------------------------------------------------------------------
_SCANNER_ROUTE_PREFIXES: tuple[str, ...] = (
    "/.env",
    "/.git",
    "/.svn",
    "/wp-",
    "/wordpress",
    "/admin",
    "/phpmyadmin",
    "/mysqladmin",
    "/actuator",
    "/api/v1/pods",       # k8s probing
    "/console",           # jboss / spring boot console
    "/manager/html",      # tomcat
    "/cgi-bin",
    "/shell",
    "/cmd",
    "/.well-known/security",  # sometimes abused by scanners
    "/boaform",
    "/HNAP1",
    "/setup.php",
    "/_ignition",
    "/vendor/",
    "/config/",
    "/server-status",
)

# ---------------------------------------------------------------------------
# Bot / scanner user-agent substrings (case-insensitive)
# ---------------------------------------------------------------------------
_BOT_UA_SUBSTRINGS: tuple[str, ...] = (
    "sqlmap",
    "nuclei",
    "zgrab",
    "masscan",
    "nmap",
    "nikto",
    "dirbuster",
    "gobuster",
    "ffuf",
    "wfuzz",
    "hydra",
    "medusa",
    "burpsuite",
    "burp suite",
    "zap/",         # OWASP ZAP
    "python-requests/2",  # raw requests lib without a custom UA — common in scripts
    "go-http-client",
    "curl/",         # curl on scanner paths only; matched after route check
    "libwww-perl",
    "petalbot",
    "ahrefsbot",
    "semrushbot",
    "mj12bot",
    "dotbot",
    "scrapy",
    "wget/",
)


def _get_str_attr(span: "ReadableSpan", key: str) -> str:
    """Return a span attribute as a lowercase string, or empty string."""
    if not hasattr(span, "attributes") or not span.attributes:
        return ""
    val = span.attributes.get(key, "")
    return str(val).lower() if val else ""


def _is_scanner_route(route: str, url: str) -> bool:
    """Return True if the HTTP route/URL matches a known scanner pattern."""
    for prefix in _SCANNER_ROUTE_PREFIXES:
        if route.startswith(prefix) or url.startswith(prefix):
            return True
    return False


def _is_bot_user_agent(ua: str) -> bool:
    """Return True if the user-agent contains a known bot/scanner keyword."""
    for keyword in _BOT_UA_SUBSTRINGS:
        if keyword in ua:
            return True
    return False


class BotFilterSpanProcessor(SpanProcessor):
    """
    A SpanProcessor that drops spans generated by bot/scanner traffic.

    Register this FIRST in the TracerProvider so bot spans never reach
    the BatchSpanProcessor or Tempo.

    Example registration (in opentelemetry_config.py):
        cls._tracer_provider.add_span_processor(BotFilterSpanProcessor())
    """

    def __init__(self) -> None:
        self._dropped_total = 0
        self._next: Optional[SpanProcessor] = None  # unused; we break the chain on drop
        logger.info("🤖 BotFilterSpanProcessor registered — bot traces will be dropped silently")

    # ------------------------------------------------------------------
    # SpanProcessor interface
    # ------------------------------------------------------------------

    def on_start(self, span, parent_context=None) -> None:
        """Called when a span starts — no filtering here (attributes not set yet)."""
        pass

    def on_end(self, span: "ReadableSpan") -> None:
        """
        Called when a span ends. Inspect attributes and drop if bot traffic.

        Because we do NOT call any downstream processor here on a drop,
        the span is permanently discarded from the export pipeline.
        """
        if not _OTEL_AVAILABLE:
            return

        reason = self._classify(span)
        if reason:
            self._dropped_total += 1
            _increment_dropped_counter(reason)
            logger.debug(
                "🤖 Bot trace dropped: reason=%s route=%s ua=%s status=%s",
                reason,
                _get_str_attr(span, "http.route") or _get_str_attr(span, "http.url"),
                _get_str_attr(span, "http.user_agent")[:60],
                _get_str_attr(span, "http.status_code"),
            )
            return  # ← span is gone; no downstream on_end() called

        # Legitimate span — do nothing here; TracerProvider calls each registered
        # processor independently, so the downstream processors will still receive
        # this span. BotFilterSpanProcessor only needs to suppress drops.

    def shutdown(self) -> None:
        logger.info(
            "🤖 BotFilterSpanProcessor shutdown — total bot traces dropped: %d",
            self._dropped_total,
        )

    def force_flush(self, timeout_millis: int = 30000) -> bool:
        return True

    # ------------------------------------------------------------------
    # Internal classification logic
    # ------------------------------------------------------------------

    def _classify(self, span: "ReadableSpan") -> Optional[str]:
        """
        Return the drop reason string if this span should be dropped, else None.
        """
        route = _get_str_attr(span, "http.route")
        # http.target includes query string; http.url is the full URL
        url = _get_str_attr(span, "http.target") or _get_str_attr(span, "url.path") or ""
        ua = _get_str_attr(span, "http.user_agent") or _get_str_attr(span, "user_agent.original")
        status = _get_str_attr(span, "http.status_code") or _get_str_attr(span, "http.response.status_code")
        has_customer = bool(
            _get_str_attr(span, "customer.id")
            or _get_str_attr(span, "user.id")
            or _get_str_attr(span, "enduser.id")
        )

        # Rule 1: Scanner route
        if route or url:
            if _is_scanner_route(route, url):
                return "scanner_route"

        # Rule 2: Bot user-agent
        if ua and _is_bot_user_agent(ua):
            return "bot_user_agent"

        # Rule 3: Unauthenticated 401/403 flood (credential brute-force probing)
        if status in ("401", "403") and not has_customer:
            return "unauth_4xx_flood"

        # Rule 4: Unauthenticated 429 (rate-limit spam — key scanner never
        # authenticated so no customer.id/user.id is set on the span)
        if status == "429" and not has_customer:
            return "unauth_429_spam"

        return None

    @property
    def dropped_count(self) -> int:
        """Total spans dropped since startup (for health checks / logging)."""
        return self._dropped_total


# ---------------------------------------------------------------------------
# Prometheus counter — imported lazily to avoid circular imports at load time
# ---------------------------------------------------------------------------
_prom_counter = None
_prom_import_attempted = False


def _increment_dropped_counter(reason: str) -> None:
    """Increment the Prometheus bot_traces_dropped_total counter (lazy import)."""
    global _prom_counter, _prom_import_attempted
    if _prom_import_attempted and _prom_counter is None:
        return  # prometheus_metrics failed to load previously — skip silently

    if not _prom_import_attempted:
        _prom_import_attempted = True
        try:
            from src.services.prometheus_metrics import bot_traces_dropped_total

            _prom_counter = bot_traces_dropped_total
        except Exception:
            _prom_counter = None

    if _prom_counter is not None:
        try:
            _prom_counter.labels(reason=reason).inc()
        except Exception:
            pass
