-- Seed model_quality_scores from QUALITY_PRIORS in model_selector.py
-- 15 models × 12 task types = 180 rows
-- Source: src/services/model_selector.py QUALITY_PRIORS dict

INSERT INTO model_quality_scores (model_id, task_type, score, source) VALUES
-- openai/gpt-4o
('openai/gpt-4o', 'simple_qa', 92, 'manual'),
('openai/gpt-4o', 'complex_reasoning', 95, 'manual'),
('openai/gpt-4o', 'code_generation', 94, 'manual'),
('openai/gpt-4o', 'code_review', 93, 'manual'),
('openai/gpt-4o', 'creative_writing', 90, 'manual'),
('openai/gpt-4o', 'summarization', 91, 'manual'),
('openai/gpt-4o', 'translation', 88, 'manual'),
('openai/gpt-4o', 'math_calculation', 93, 'manual'),
('openai/gpt-4o', 'data_analysis', 90, 'manual'),
('openai/gpt-4o', 'conversation', 90, 'manual'),
('openai/gpt-4o', 'tool_use', 95, 'manual'),
('openai/gpt-4o', 'unknown', 88, 'manual'),
-- openai/gpt-4o-mini
('openai/gpt-4o-mini', 'simple_qa', 85, 'manual'),
('openai/gpt-4o-mini', 'complex_reasoning', 78, 'manual'),
('openai/gpt-4o-mini', 'code_generation', 82, 'manual'),
('openai/gpt-4o-mini', 'code_review', 80, 'manual'),
('openai/gpt-4o-mini', 'creative_writing', 84, 'manual'),
('openai/gpt-4o-mini', 'summarization', 86, 'manual'),
('openai/gpt-4o-mini', 'translation', 82, 'manual'),
('openai/gpt-4o-mini', 'math_calculation', 80, 'manual'),
('openai/gpt-4o-mini', 'data_analysis', 78, 'manual'),
('openai/gpt-4o-mini', 'conversation', 85, 'manual'),
('openai/gpt-4o-mini', 'tool_use', 88, 'manual'),
('openai/gpt-4o-mini', 'unknown', 80, 'manual'),
-- anthropic/claude-3.5-sonnet
('anthropic/claude-3.5-sonnet', 'simple_qa', 93, 'manual'),
('anthropic/claude-3.5-sonnet', 'complex_reasoning', 94, 'manual'),
('anthropic/claude-3.5-sonnet', 'code_generation', 96, 'manual'),
('anthropic/claude-3.5-sonnet', 'code_review', 95, 'manual'),
('anthropic/claude-3.5-sonnet', 'creative_writing', 92, 'manual'),
('anthropic/claude-3.5-sonnet', 'summarization', 93, 'manual'),
('anthropic/claude-3.5-sonnet', 'translation', 85, 'manual'),
('anthropic/claude-3.5-sonnet', 'math_calculation', 88, 'manual'),
('anthropic/claude-3.5-sonnet', 'data_analysis', 90, 'manual'),
('anthropic/claude-3.5-sonnet', 'conversation', 92, 'manual'),
('anthropic/claude-3.5-sonnet', 'tool_use', 93, 'manual'),
('anthropic/claude-3.5-sonnet', 'unknown', 90, 'manual'),
-- anthropic/claude-3-haiku
('anthropic/claude-3-haiku', 'simple_qa', 82, 'manual'),
('anthropic/claude-3-haiku', 'complex_reasoning', 72, 'manual'),
('anthropic/claude-3-haiku', 'code_generation', 78, 'manual'),
('anthropic/claude-3-haiku', 'code_review', 75, 'manual'),
('anthropic/claude-3-haiku', 'creative_writing', 80, 'manual'),
('anthropic/claude-3-haiku', 'summarization', 84, 'manual'),
('anthropic/claude-3-haiku', 'translation', 78, 'manual'),
('anthropic/claude-3-haiku', 'math_calculation', 72, 'manual'),
('anthropic/claude-3-haiku', 'data_analysis', 70, 'manual'),
('anthropic/claude-3-haiku', 'conversation', 82, 'manual'),
('anthropic/claude-3-haiku', 'tool_use', 80, 'manual'),
('anthropic/claude-3-haiku', 'unknown', 75, 'manual'),
-- anthropic/claude-3-sonnet
('anthropic/claude-3-sonnet', 'simple_qa', 88, 'manual'),
('anthropic/claude-3-sonnet', 'complex_reasoning', 85, 'manual'),
('anthropic/claude-3-sonnet', 'code_generation', 88, 'manual'),
('anthropic/claude-3-sonnet', 'code_review', 86, 'manual'),
('anthropic/claude-3-sonnet', 'creative_writing', 87, 'manual'),
('anthropic/claude-3-sonnet', 'summarization', 89, 'manual'),
('anthropic/claude-3-sonnet', 'translation', 82, 'manual'),
('anthropic/claude-3-sonnet', 'math_calculation', 82, 'manual'),
('anthropic/claude-3-sonnet', 'data_analysis', 84, 'manual'),
('anthropic/claude-3-sonnet', 'conversation', 88, 'manual'),
('anthropic/claude-3-sonnet', 'tool_use', 88, 'manual'),
('anthropic/claude-3-sonnet', 'unknown', 84, 'manual'),
-- google/gemini-flash-1.5
('google/gemini-flash-1.5', 'simple_qa', 80, 'manual'),
('google/gemini-flash-1.5', 'complex_reasoning', 75, 'manual'),
('google/gemini-flash-1.5', 'code_generation', 78, 'manual'),
('google/gemini-flash-1.5', 'code_review', 75, 'manual'),
('google/gemini-flash-1.5', 'creative_writing', 78, 'manual'),
('google/gemini-flash-1.5', 'summarization', 82, 'manual'),
('google/gemini-flash-1.5', 'translation', 80, 'manual'),
('google/gemini-flash-1.5', 'math_calculation', 78, 'manual'),
('google/gemini-flash-1.5', 'data_analysis', 76, 'manual'),
('google/gemini-flash-1.5', 'conversation', 80, 'manual'),
('google/gemini-flash-1.5', 'tool_use', 75, 'manual'),
('google/gemini-flash-1.5', 'unknown', 76, 'manual'),
-- google/gemini-pro-1.5
('google/gemini-pro-1.5', 'simple_qa', 88, 'manual'),
('google/gemini-pro-1.5', 'complex_reasoning', 86, 'manual'),
('google/gemini-pro-1.5', 'code_generation', 85, 'manual'),
('google/gemini-pro-1.5', 'code_review', 84, 'manual'),
('google/gemini-pro-1.5', 'creative_writing', 85, 'manual'),
('google/gemini-pro-1.5', 'summarization', 88, 'manual'),
('google/gemini-pro-1.5', 'translation', 85, 'manual'),
('google/gemini-pro-1.5', 'math_calculation', 85, 'manual'),
('google/gemini-pro-1.5', 'data_analysis', 86, 'manual'),
('google/gemini-pro-1.5', 'conversation', 87, 'manual'),
('google/gemini-pro-1.5', 'tool_use', 82, 'manual'),
('google/gemini-pro-1.5', 'unknown', 84, 'manual'),
-- deepseek/deepseek-chat
('deepseek/deepseek-chat', 'simple_qa', 78, 'manual'),
('deepseek/deepseek-chat', 'complex_reasoning', 82, 'manual'),
('deepseek/deepseek-chat', 'code_generation', 90, 'manual'),
('deepseek/deepseek-chat', 'code_review', 88, 'manual'),
('deepseek/deepseek-chat', 'creative_writing', 72, 'manual'),
('deepseek/deepseek-chat', 'summarization', 78, 'manual'),
('deepseek/deepseek-chat', 'translation', 75, 'manual'),
('deepseek/deepseek-chat', 'math_calculation', 85, 'manual'),
('deepseek/deepseek-chat', 'data_analysis', 82, 'manual'),
('deepseek/deepseek-chat', 'conversation', 76, 'manual'),
('deepseek/deepseek-chat', 'tool_use', 80, 'manual'),
('deepseek/deepseek-chat', 'unknown', 78, 'manual'),
-- deepseek/deepseek-coder
('deepseek/deepseek-coder', 'simple_qa', 70, 'manual'),
('deepseek/deepseek-coder', 'complex_reasoning', 75, 'manual'),
('deepseek/deepseek-coder', 'code_generation', 94, 'manual'),
('deepseek/deepseek-coder', 'code_review', 92, 'manual'),
('deepseek/deepseek-coder', 'creative_writing', 60, 'manual'),
('deepseek/deepseek-coder', 'summarization', 70, 'manual'),
('deepseek/deepseek-coder', 'translation', 65, 'manual'),
('deepseek/deepseek-coder', 'math_calculation', 80, 'manual'),
('deepseek/deepseek-coder', 'data_analysis', 78, 'manual'),
('deepseek/deepseek-coder', 'conversation', 68, 'manual'),
('deepseek/deepseek-coder', 'tool_use', 82, 'manual'),
('deepseek/deepseek-coder', 'unknown', 72, 'manual'),
-- meta-llama/llama-3.1-8b-instant
('meta-llama/llama-3.1-8b-instant', 'simple_qa', 75, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'complex_reasoning', 68, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'code_generation', 72, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'code_review', 70, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'creative_writing', 74, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'summarization', 76, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'translation', 72, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'math_calculation', 68, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'data_analysis', 66, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'conversation', 76, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'tool_use', 65, 'manual'),
('meta-llama/llama-3.1-8b-instant', 'unknown', 70, 'manual'),
-- meta-llama/llama-3.1-70b
('meta-llama/llama-3.1-70b', 'simple_qa', 85, 'manual'),
('meta-llama/llama-3.1-70b', 'complex_reasoning', 82, 'manual'),
('meta-llama/llama-3.1-70b', 'code_generation', 84, 'manual'),
('meta-llama/llama-3.1-70b', 'code_review', 82, 'manual'),
('meta-llama/llama-3.1-70b', 'creative_writing', 83, 'manual'),
('meta-llama/llama-3.1-70b', 'summarization', 85, 'manual'),
('meta-llama/llama-3.1-70b', 'translation', 80, 'manual'),
('meta-llama/llama-3.1-70b', 'math_calculation', 80, 'manual'),
('meta-llama/llama-3.1-70b', 'data_analysis', 82, 'manual'),
('meta-llama/llama-3.1-70b', 'conversation', 84, 'manual'),
('meta-llama/llama-3.1-70b', 'tool_use', 78, 'manual'),
('meta-llama/llama-3.1-70b', 'unknown', 80, 'manual'),
-- meta-llama/llama-3.1-405b
('meta-llama/llama-3.1-405b', 'simple_qa', 90, 'manual'),
('meta-llama/llama-3.1-405b', 'complex_reasoning', 88, 'manual'),
('meta-llama/llama-3.1-405b', 'code_generation', 88, 'manual'),
('meta-llama/llama-3.1-405b', 'code_review', 86, 'manual'),
('meta-llama/llama-3.1-405b', 'creative_writing', 87, 'manual'),
('meta-llama/llama-3.1-405b', 'summarization', 89, 'manual'),
('meta-llama/llama-3.1-405b', 'translation', 85, 'manual'),
('meta-llama/llama-3.1-405b', 'math_calculation', 86, 'manual'),
('meta-llama/llama-3.1-405b', 'data_analysis', 87, 'manual'),
('meta-llama/llama-3.1-405b', 'conversation', 88, 'manual'),
('meta-llama/llama-3.1-405b', 'tool_use', 82, 'manual'),
('meta-llama/llama-3.1-405b', 'unknown', 85, 'manual'),
-- mistral/mistral-small
('mistral/mistral-small', 'simple_qa', 78, 'manual'),
('mistral/mistral-small', 'complex_reasoning', 72, 'manual'),
('mistral/mistral-small', 'code_generation', 75, 'manual'),
('mistral/mistral-small', 'code_review', 73, 'manual'),
('mistral/mistral-small', 'creative_writing', 76, 'manual'),
('mistral/mistral-small', 'summarization', 80, 'manual'),
('mistral/mistral-small', 'translation', 82, 'manual'),
('mistral/mistral-small', 'math_calculation', 72, 'manual'),
('mistral/mistral-small', 'data_analysis', 70, 'manual'),
('mistral/mistral-small', 'conversation', 78, 'manual'),
('mistral/mistral-small', 'tool_use', 72, 'manual'),
('mistral/mistral-small', 'unknown', 74, 'manual'),
-- mistral/mistral-large
('mistral/mistral-large', 'simple_qa', 86, 'manual'),
('mistral/mistral-large', 'complex_reasoning', 84, 'manual'),
('mistral/mistral-large', 'code_generation', 85, 'manual'),
('mistral/mistral-large', 'code_review', 83, 'manual'),
('mistral/mistral-large', 'creative_writing', 84, 'manual'),
('mistral/mistral-large', 'summarization', 87, 'manual'),
('mistral/mistral-large', 'translation', 88, 'manual'),
('mistral/mistral-large', 'math_calculation', 82, 'manual'),
('mistral/mistral-large', 'data_analysis', 84, 'manual'),
('mistral/mistral-large', 'conversation', 86, 'manual'),
('mistral/mistral-large', 'tool_use', 84, 'manual'),
('mistral/mistral-large', 'unknown', 83, 'manual'),
-- cohere/command-r-plus
('cohere/command-r-plus', 'simple_qa', 84, 'manual'),
('cohere/command-r-plus', 'complex_reasoning', 80, 'manual'),
('cohere/command-r-plus', 'code_generation', 78, 'manual'),
('cohere/command-r-plus', 'code_review', 76, 'manual'),
('cohere/command-r-plus', 'creative_writing', 82, 'manual'),
('cohere/command-r-plus', 'summarization', 86, 'manual'),
('cohere/command-r-plus', 'translation', 80, 'manual'),
('cohere/command-r-plus', 'math_calculation', 75, 'manual'),
('cohere/command-r-plus', 'data_analysis', 80, 'manual'),
('cohere/command-r-plus', 'conversation', 84, 'manual'),
('cohere/command-r-plus', 'tool_use', 82, 'manual'),
('cohere/command-r-plus', 'unknown', 78, 'manual')
ON CONFLICT (model_id, task_type) DO NOTHING;
