-- Migration: Seed model mapping tables from Python constants
-- Source: src/services/model_transformations.py (MODEL_ID_ALIASES, MODEL_PROVIDER_OVERRIDES, _MODEL_ID_MAPPINGS)
-- All inserts use ON CONFLICT DO NOTHING to be idempotent and safe to re-run.

-- ============================================================
-- 1. model_aliases  (107 entries from MODEL_ID_ALIASES)
-- ============================================================
INSERT INTO model_aliases (alias, canonical_id) VALUES
  -- OpenAI GPT models without org prefix
  ('gpt-4', 'openai/gpt-4'),
  ('gpt-4-turbo', 'openai/gpt-4-turbo'),
  ('gpt-4-turbo-preview', 'openai/gpt-4-turbo-preview'),
  ('gpt-4o', 'openai/gpt-4o'),
  ('gpt-4o-mini', 'openai/gpt-4o-mini'),
  ('gpt-4o-mini-2024-07-18', 'openai/gpt-4o-mini-2024-07-18'),
  ('gpt-4o-2024-05-13', 'openai/gpt-4o-2024-05-13'),
  ('gpt-4o-2024-08-06', 'openai/gpt-4o-2024-08-06'),
  ('gpt-4o-2024-11-20', 'openai/gpt-4o-2024-11-20'),
  ('gpt-4-0125-preview', 'openai/gpt-4-0125-preview'),
  ('gpt-4-1106-preview', 'openai/gpt-4-1106-preview'),
  ('gpt-4-vision-preview', 'openai/gpt-4-vision-preview'),
  ('gpt-3.5-turbo', 'openai/gpt-3.5-turbo'),
  ('gpt-3.5-turbo-16k', 'openai/gpt-3.5-turbo-16k'),
  ('gpt-3.5-turbo-0125', 'openai/gpt-3.5-turbo-0125'),
  ('gpt-3.5-turbo-1106', 'openai/gpt-3.5-turbo-1106'),
  -- GPT-5.1 variants
  ('openai/gpt-5-1', 'openai/gpt-5.1'),
  ('openai/gpt5-1', 'openai/gpt-5.1'),
  ('openai/gpt5.1', 'openai/gpt-5.1'),
  ('openai/gpt-5_1', 'openai/gpt-5.1'),
  ('openai/gpt5_1', 'openai/gpt-5.1'),
  ('gpt-5-1', 'openai/gpt-5.1'),
  ('gpt5-1', 'openai/gpt-5.1'),
  ('gpt-5_1', 'openai/gpt-5.1'),
  ('gpt5_1', 'openai/gpt-5.1'),
  ('gpt5.1', 'openai/gpt-5.1'),
  ('gpt-5.1', 'openai/gpt-5.1'),
  -- OpenAI o-series
  ('o1', 'openai/o1'),
  ('o1-pro', 'openai/o1-pro'),
  ('o3', 'openai/o3'),
  ('o3-mini', 'openai/o3-mini'),
  ('o3-mini-high', 'openai/o3-mini-high'),
  ('o3-pro', 'openai/o3-pro'),
  ('o3-deep-research', 'openai/o3-deep-research'),
  ('o4-mini', 'openai/o4-mini'),
  ('o4-mini-high', 'openai/o4-mini-high'),
  ('o4-mini-deep-research', 'openai/o4-mini-deep-research'),
  -- Anthropic Claude models
  ('claude-3-opus', 'anthropic/claude-3-opus'),
  ('claude-3-sonnet', 'anthropic/claude-3-sonnet'),
  ('claude-3-haiku', 'anthropic/claude-3-haiku'),
  ('claude-3.5-sonnet', 'anthropic/claude-3.5-sonnet'),
  ('claude-3.5-haiku', 'anthropic/claude-3.5-haiku'),
  ('claude-3.7-sonnet', 'anthropic/claude-3.7-sonnet'),
  ('claude-opus-4', 'anthropic/claude-opus-4'),
  ('claude-opus-4.1', 'anthropic/claude-opus-4.1'),
  ('claude-opus-4.5', 'anthropic/claude-opus-4.5'),
  ('opus-4', 'anthropic/claude-opus-4'),
  ('opus-4.1', 'anthropic/claude-opus-4.1'),
  ('opus-4.5', 'anthropic/claude-opus-4.5'),
  ('claude-sonnet-4', 'anthropic/claude-sonnet-4'),
  ('sonnet-4', 'anthropic/claude-sonnet-4'),
  ('claude-sonnet-4-20250514', 'anthropic/claude-sonnet-4.5'),
  ('claude-sonnet-4.5-20250514', 'anthropic/claude-sonnet-4.5'),
  ('claude-4-5-sonnet-20250514', 'anthropic/claude-sonnet-4.5'),
  ('claude-4.5-sonnet-20250514', 'anthropic/claude-sonnet-4.5'),
  ('sonnet-4.5', 'anthropic/claude-sonnet-4.5'),
  ('claude-sonnet-4.5', 'anthropic/claude-sonnet-4.5'),
  ('claude-opus-4-20250514', 'anthropic/claude-opus-4.5'),
  ('claude-opus-4.5-20250514', 'anthropic/claude-opus-4.5'),
  ('claude-4-5-opus-20250514', 'anthropic/claude-opus-4.5'),
  ('claude-4.5-opus-20250514', 'anthropic/claude-opus-4.5'),
  ('claude-3-5-sonnet-20241022', 'anthropic/claude-3.5-sonnet'),
  ('claude-3-5-haiku-20241022', 'anthropic/claude-3.5-haiku'),
  ('claude-haiku-4.5', 'anthropic/claude-haiku-4.5'),
  ('haiku-4.5', 'anthropic/claude-haiku-4.5'),
  -- DeepSeek
  ('deepseek-r1', 'deepseek/deepseek-r1'),
  ('r1', 'deepseek/deepseek-r1'),
  ('deepseek-v3.2', 'deepseek/deepseek-v3.2'),
  -- Meta Llama 4
  ('llama-4-scout', 'meta-llama/llama-4-scout'),
  ('llama-4-maverick', 'meta-llama/llama-4-maverick'),
  -- Google Gemini 3
  ('gemini-3', 'google/gemini-3-flash-preview'),
  ('gemini-3-flash', 'google/gemini-3-flash-preview'),
  ('gemini-3-pro', 'google/gemini-3-pro-preview'),
  -- XAI Grok 3
  ('grok-3', 'x-ai/grok-3'),
  ('grok-3-beta', 'x-ai/grok-3-beta'),
  ('grok-3-mini', 'x-ai/grok-3-mini'),
  ('grok-3-mini-beta', 'x-ai/grok-3-mini-beta'),
  -- XAI Grok 4
  ('grok-4', 'x-ai/grok-4'),
  ('grok-4-fast', 'x-ai/grok-4-fast'),
  ('grok-4.1-fast', 'x-ai/grok-4.1-fast'),
  ('grok-code-fast-1', 'x-ai/grok-code-fast-1'),
  -- XAI deprecated → grok-3
  ('grok-beta', 'x-ai/grok-3'),
  ('xai/grok-beta', 'x-ai/grok-3'),
  ('grok-vision-beta', 'x-ai/grok-3'),
  ('xai/grok-vision-beta', 'x-ai/grok-3'),
  ('grok-2', 'x-ai/grok-3'),
  ('grok-2-1212', 'x-ai/grok-3'),
  ('xai/grok-2', 'x-ai/grok-3'),
  ('xai/grok-2-1212', 'x-ai/grok-3'),
  ('x-ai/grok-2', 'x-ai/grok-3'),
  ('x-ai/grok-2-1212', 'x-ai/grok-3'),
  -- Zhipu AI GLM (z-ai/ prefix)
  ('z-ai/glm-4.7', 'z-ai/glm-4-flash'),
  ('z-ai/glm-4-7', 'z-ai/glm-4-flash'),
  ('z-ai/glm4.7', 'z-ai/glm-4-flash'),
  ('z-ai/glm-4.5', 'z-ai/glm-4-flash'),
  ('z-ai/glm-4.6', 'z-ai/glm-4-flash'),
  -- Zhipu AI GLM (zai/ prefix and bare names)
  ('zai/glm-4.7', 'z-ai/glm-4-flash'),
  ('zai/glm-4.6v', 'z-ai/glm-4-flash'),
  ('zai/glm-4.5-air', 'z-ai/glm-4-flash'),
  ('zai/glm-4.5', 'z-ai/glm-4-flash'),
  ('glm-4.7', 'z-ai/glm-4-flash'),
  ('glm-4.6v', 'z-ai/glm-4-flash'),
  ('glm-4.5-air', 'z-ai/glm-4-flash'),
  ('glm-4.5', 'z-ai/glm-4-flash'),
  -- Black Forest Labs FLUX
  ('bfl/flux-1.1-pro', 'bfl/flux-1-1-pro'),
  ('bfl/flux1.1-pro', 'bfl/flux-1-1-pro'),
  ('bfl/flux1-1-pro', 'bfl/flux-1-1-pro')
ON CONFLICT (alias) DO NOTHING;


-- ============================================================
-- 2. model_routing_rules  (78 entries from MODEL_PROVIDER_OVERRIDES)
-- ============================================================
INSERT INTO model_routing_rules (model_pattern, force_provider, priority) VALUES
  ('katanemo/arch-router-1.5b', 'huggingface', 0),
  ('zai-org/glm-4.6-fp8', 'near', 0),
  ('c10x/longwriter-qwen2.5-7b-instruct', 'featherless', 0),
  ('meta/llama-3-8b-instruct', 'openrouter', 0),
  ('bfl/flux-1-1-pro', 'fal', 0),
  ('bfl/flux-1.1-pro', 'fal', 0),
  -- DeepSeek → openrouter (not on Fireworks)
  ('deepseek/deepseek-v3.2', 'openrouter', 0),
  ('deepseek-ai/deepseek-v3.2', 'openrouter', 0),
  ('deepseek-v3.2', 'openrouter', 0),
  ('deepseek/deepseek-v2', 'openrouter', 0),
  ('deepseek-ai/deepseek-v2', 'openrouter', 0),
  ('deepseek-v2', 'openrouter', 0),
  ('deepseek/deepseek-v2.5', 'openrouter', 0),
  ('deepseek-ai/deepseek-v2.5', 'openrouter', 0),
  ('deepseek-v2.5', 'openrouter', 0),
  ('deepseek/deepseek-coder', 'openrouter', 0),
  ('deepseek-ai/deepseek-coder', 'openrouter', 0),
  ('deepseek-coder', 'openrouter', 0),
  ('deepseek/deepseek-chat', 'openrouter', 0),
  ('deepseek-ai/deepseek-chat', 'openrouter', 0),
  ('deepseek-chat', 'openrouter', 0),
  ('deepseek/deepseek-chat-v3', 'openrouter', 0),
  ('deepseek/deepseek-chat-v3.1', 'openrouter', 0),
  ('deepseek/deepseek-chat-v3-0324', 'openrouter', 0),
  ('deepseek-ai/deepseek-chat-v3', 'openrouter', 0),
  ('deepseek-ai/deepseek-chat-v3.1', 'openrouter', 0),
  ('deepseek-ai/deepseek-chat-v3-0324', 'openrouter', 0),
  ('deepseek-chat-v3', 'openrouter', 0),
  ('deepseek-chat-v3.1', 'openrouter', 0),
  ('deepseek-chat-v3-0324', 'openrouter', 0),
  -- Google Gemini → google-vertex (Gemini 3 series)
  ('gemini-3', 'google-vertex', 0),
  ('gemini-3-flash', 'google-vertex', 0),
  ('gemini-3-flash-preview', 'google-vertex', 0),
  ('gemini-3-pro', 'google-vertex', 0),
  ('gemini-3-pro-preview', 'google-vertex', 0),
  ('google/gemini-3', 'google-vertex', 0),
  ('google/gemini-3-flash', 'google-vertex', 0),
  ('google/gemini-3-flash-preview', 'google-vertex', 0),
  ('google/gemini-3-pro', 'google-vertex', 0),
  ('google/gemini-3-pro-preview', 'google-vertex', 0),
  -- Gemini 2.5 series
  ('gemini-2.5', 'google-vertex', 0),
  ('gemini-2.5-flash', 'google-vertex', 0),
  ('gemini-2.5-flash-lite', 'google-vertex', 0),
  ('gemini-2.5-flash-preview', 'google-vertex', 0),
  ('gemini-2.5-flash-image', 'google-vertex', 0),
  ('gemini-2.5-pro', 'google-vertex', 0),
  ('gemini-2.5-pro-preview', 'google-vertex', 0),
  ('google/gemini-2.5', 'google-vertex', 0),
  ('google/gemini-2.5-flash', 'google-vertex', 0),
  ('google/gemini-2.5-flash-lite', 'google-vertex', 0),
  ('google/gemini-2.5-flash-preview', 'google-vertex', 0),
  ('google/gemini-2.5-flash-image', 'google-vertex', 0),
  ('google/gemini-2.5-pro', 'google-vertex', 0),
  ('google/gemini-2.5-pro-preview', 'google-vertex', 0),
  -- Gemini 2.0 series
  ('gemini-2.0', 'google-vertex', 0),
  ('gemini-2.0-flash', 'google-vertex', 0),
  ('gemini-2.0-flash-thinking', 'google-vertex', 0),
  ('gemini-2.0-flash-exp', 'google-vertex', 0),
  ('gemini-2.0-pro', 'google-vertex', 0),
  ('google/gemini-2.0', 'google-vertex', 0),
  ('google/gemini-2.0-flash', 'google-vertex', 0),
  ('google/gemini-2.0-flash-thinking', 'google-vertex', 0),
  ('google/gemini-2.0-flash-exp', 'google-vertex', 0),
  ('google/gemini-2.0-pro', 'google-vertex', 0),
  -- Gemini 1.5 series
  ('gemini-1.5', 'google-vertex', 0),
  ('gemini-1.5-flash', 'google-vertex', 0),
  ('gemini-1.5-pro', 'google-vertex', 0),
  ('google/gemini-1.5', 'google-vertex', 0),
  ('google/gemini-1.5-flash', 'google-vertex', 0),
  ('google/gemini-1.5-pro', 'google-vertex', 0),
  -- Gemini 1.0 series
  ('gemini-1.0', 'google-vertex', 0),
  ('gemini-1.0-pro', 'google-vertex', 0),
  ('gemini-1.0-pro-vision', 'google-vertex', 0),
  ('google/gemini-1.0', 'google-vertex', 0),
  ('google/gemini-1.0-pro', 'google-vertex', 0),
  ('google/gemini-1.0-pro-vision', 'google-vertex', 0),
  -- Generic Gemini
  ('gemini', 'google-vertex', 0),
  ('google/gemini', 'google-vertex', 0)
ON CONFLICT (model_pattern) DO NOTHING;


-- ============================================================
-- 3. model_provider_mappings  (~504 entries from _MODEL_ID_MAPPINGS)
-- ============================================================

-- ---- fireworks ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('deepseek-ai/deepseek-v3', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek-ai/deepseek-v3.1', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek-ai/deepseek-v3p1', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek-ai/deepseek-r1', 'fireworks', 'accounts/fireworks/models/deepseek-r1-0528'),
  ('deepseek/deepseek-v3', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek/deepseek-v3.1', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek/deepseek-v3p1', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek/deepseek-r1', 'fireworks', 'accounts/fireworks/models/deepseek-r1-0528'),
  ('meta-llama/llama-3.3-70b', 'fireworks', 'accounts/fireworks/models/llama-v3p3-70b-instruct'),
  ('meta-llama/llama-3.3-70b-instruct', 'fireworks', 'accounts/fireworks/models/llama-v3p3-70b-instruct'),
  ('meta-llama/llama-3.1-70b', 'fireworks', 'accounts/fireworks/models/llama-v3p1-70b-instruct'),
  ('meta-llama/llama-3.1-70b-instruct', 'fireworks', 'accounts/fireworks/models/llama-v3p1-70b-instruct'),
  ('meta-llama/llama-3.1-8b', 'fireworks', 'accounts/fireworks/models/llama-v3p1-8b-instruct'),
  ('meta-llama/llama-3.1-8b-instruct', 'fireworks', 'accounts/fireworks/models/llama-v3p1-8b-instruct'),
  ('meta-llama/llama-4-scout', 'fireworks', 'accounts/fireworks/models/llama4-scout-instruct-basic'),
  ('meta-llama/llama-4-maverick', 'fireworks', 'accounts/fireworks/models/llama4-maverick-instruct-basic'),
  ('deepseek-v3', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek-v3.1', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek-v3p1', 'fireworks', 'accounts/fireworks/models/deepseek-v3p1'),
  ('deepseek-r1', 'fireworks', 'accounts/fireworks/models/deepseek-r1-0528'),
  ('llama-3.3-70b', 'fireworks', 'accounts/fireworks/models/llama-v3p3-70b-instruct'),
  ('llama-3.1-70b', 'fireworks', 'accounts/fireworks/models/llama-v3p1-70b-instruct'),
  ('llama-3.1-8b', 'fireworks', 'accounts/fireworks/models/llama-v3p1-8b-instruct'),
  ('qwen/qwen-2.5-32b', 'fireworks', 'accounts/fireworks/models/qwen2p5-vl-32b-instruct'),
  ('qwen/qwen-3-235b', 'fireworks', 'accounts/fireworks/models/qwen3-235b-a22b'),
  ('qwen/qwen-3-235b-instruct', 'fireworks', 'accounts/fireworks/models/qwen3-235b-a22b-instruct-2507'),
  ('qwen/qwen-3-235b-thinking', 'fireworks', 'accounts/fireworks/models/qwen3-235b-a22b-thinking-2507'),
  ('qwen/qwen-3-30b-thinking', 'fireworks', 'accounts/fireworks/models/qwen3-30b-a3b-thinking-2507'),
  ('qwen/qwen-3-coder-480b', 'fireworks', 'accounts/fireworks/models/qwen3-coder-480b-a35b-instruct'),
  ('moonshot-ai/kimi-k2', 'fireworks', 'accounts/fireworks/models/kimi-k2-instruct'),
  ('moonshot-ai/kimi-k2-instruct', 'fireworks', 'accounts/fireworks/models/kimi-k2-instruct'),
  ('zhipu-ai/glm-4.5', 'fireworks', 'accounts/fireworks/models/glm-4p5'),
  ('gpt-oss/gpt-120b', 'fireworks', 'accounts/fireworks/models/gpt-oss-120b'),
  ('gpt-oss/gpt-20b', 'fireworks', 'accounts/fireworks/models/gpt-oss-20b')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- openrouter ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('openai/gpt-4', 'openrouter', 'openai/gpt-4'),
  ('openai/gpt-4-turbo', 'openrouter', 'openai/gpt-4-turbo'),
  ('openai/gpt-3.5-turbo', 'openrouter', 'openai/gpt-3.5-turbo'),
  ('anthropic/claude-3-opus', 'openrouter', 'anthropic/claude-3-opus'),
  ('anthropic/claude-3-sonnet', 'openrouter', 'anthropic/claude-3-sonnet'),
  ('anthropic/claude-3-haiku', 'openrouter', 'anthropic/claude-3-haiku'),
  ('anthropic/claude-3.5-sonnet', 'openrouter', 'anthropic/claude-3.5-sonnet'),
  ('anthropic/claude-3.5-haiku', 'openrouter', 'anthropic/claude-3.5-haiku'),
  ('claude-3.5-sonnet', 'openrouter', 'anthropic/claude-3.5-sonnet'),
  ('claude-3.5-haiku', 'openrouter', 'anthropic/claude-3.5-haiku'),
  ('anthropic/claude-3.7-sonnet', 'openrouter', 'anthropic/claude-3.7-sonnet'),
  ('claude-3.7-sonnet', 'openrouter', 'anthropic/claude-3.7-sonnet'),
  ('anthropic/claude-sonnet-4', 'openrouter', 'anthropic/claude-sonnet-4'),
  ('anthropic/claude-opus-4', 'openrouter', 'anthropic/claude-opus-4'),
  ('anthropic/claude-opus-4.1', 'openrouter', 'anthropic/claude-opus-4.1'),
  ('claude-sonnet-4', 'openrouter', 'anthropic/claude-sonnet-4'),
  ('claude-opus-4', 'openrouter', 'anthropic/claude-opus-4'),
  ('claude-opus-4.1', 'openrouter', 'anthropic/claude-opus-4.1'),
  ('anthropic/claude-sonnet-4.5', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('anthropic/claude-opus-4.5', 'openrouter', 'anthropic/claude-opus-4.5'),
  ('anthropic/claude-haiku-4.5', 'openrouter', 'anthropic/claude-haiku-4.5'),
  ('anthropic/claude-4.5-sonnet', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('anthropic/claude-4.5-sonnet-20250929', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('claude-sonnet-4.5', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('claude-sonnet-4-5-20250929', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('claude-opus-4.5', 'openrouter', 'anthropic/claude-opus-4.5'),
  ('claude-haiku-4.5', 'openrouter', 'anthropic/claude-haiku-4.5'),
  ('claude-sonnet-4-20250514', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('claude-sonnet-4.5-20250514', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('claude-4-5-sonnet-20250514', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('claude-4.5-sonnet-20250514', 'openrouter', 'anthropic/claude-sonnet-4.5'),
  ('claude-opus-4-20250514', 'openrouter', 'anthropic/claude-opus-4.5'),
  ('claude-opus-4.5-20250514', 'openrouter', 'anthropic/claude-opus-4.5'),
  ('claude-4-5-opus-20250514', 'openrouter', 'anthropic/claude-opus-4.5'),
  ('claude-4.5-opus-20250514', 'openrouter', 'anthropic/claude-opus-4.5'),
  ('claude-3-5-sonnet-20241022', 'openrouter', 'anthropic/claude-3.5-sonnet'),
  ('claude-3-5-haiku-20241022', 'openrouter', 'anthropic/claude-3.5-haiku'),
  ('google/gemini-3-flash-preview', 'openrouter', 'google/gemini-3-flash-preview'),
  ('google/gemini-3-pro-preview', 'openrouter', 'google/gemini-3-pro-preview'),
  ('gemini-3-flash-preview', 'openrouter', 'google/gemini-3-flash-preview'),
  ('gemini-3-pro-preview', 'openrouter', 'google/gemini-3-pro-preview'),
  ('gemini-3-flash', 'openrouter', 'google/gemini-3-flash-preview'),
  ('gemini-3-pro', 'openrouter', 'google/gemini-3-pro-preview'),
  ('google/gemini-2.5-flash', 'openrouter', 'google/gemini-2.5-flash'),
  ('google/gemini-2.5-pro', 'openrouter', 'google/gemini-2.5-pro'),
  ('gemini-2.5-flash', 'openrouter', 'google/gemini-2.5-flash'),
  ('gemini-2.5-pro', 'openrouter', 'google/gemini-2.5-pro'),
  ('google/gemini-2.0-flash-001', 'openrouter', 'google/gemini-2.0-flash-001'),
  ('gemini-2.0-flash', 'openrouter', 'google/gemini-2.0-flash-001'),
  ('google/gemini-flash-1.5', 'openrouter', 'google/gemini-flash-1.5'),
  ('google/gemini-pro-1.5', 'openrouter', 'google/gemini-pro-1.5'),
  ('gemini-1.5-flash', 'openrouter', 'google/gemini-flash-1.5'),
  ('gemini-1.5-pro', 'openrouter', 'google/gemini-pro-1.5'),
  ('meta-llama/llama-3.1-70b', 'openrouter', 'meta-llama/llama-3.1-70b-instruct'),
  ('deepseek-ai/deepseek-v3', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek/deepseek-v3.2', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek-ai/deepseek-v3.2', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek-v3.2', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek/deepseek-v2', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek-ai/deepseek-v2', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek-v2', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek/deepseek-v2.5', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek-ai/deepseek-v2.5', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek-v2.5', 'openrouter', 'deepseek/deepseek-chat'),
  ('deepseek/deepseek-coder', 'openrouter', 'deepseek/deepseek-coder'),
  ('deepseek-ai/deepseek-coder', 'openrouter', 'deepseek/deepseek-coder'),
  ('deepseek-coder', 'openrouter', 'deepseek/deepseek-coder'),
  ('deepseek/deepseek-chat', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-ai/deepseek-chat', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-chat', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek/deepseek-chat-v3', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek/deepseek-chat-v3.1', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek/deepseek-chat-v3-0324', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-ai/deepseek-chat-v3', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-ai/deepseek-chat-v3.1', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-ai/deepseek-chat-v3-0324', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-chat-v3', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-chat-v3.1', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('deepseek-chat-v3-0324', 'openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('cerebras/llama-3.3-70b', 'openrouter', 'meta-llama/llama-3.3-70b-instruct'),
  ('cerebras/llama-3.3-70b-instruct', 'openrouter', 'meta-llama/llama-3.3-70b-instruct'),
  ('cerebras/llama-3.1-70b', 'openrouter', 'meta-llama/llama-3.1-70b-instruct'),
  ('cerebras/llama-3.1-70b-instruct', 'openrouter', 'meta-llama/llama-3.1-70b-instruct'),
  ('llama-3.3-70b', 'openrouter', 'meta-llama/llama-3.3-70b-instruct'),
  ('llama-3.1-70b', 'openrouter', 'meta-llama/llama-3.1-70b-instruct'),
  ('llama-3.1-8b', 'openrouter', 'meta-llama/llama-3.1-8b-instruct'),
  ('llama3.1-70b', 'openrouter', 'meta-llama/llama-3.1-70b-instruct'),
  ('llama3.1-8b', 'openrouter', 'meta-llama/llama-3.1-8b-instruct')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- featherless ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('deepseek-ai/deepseek-v3', 'featherless', 'deepseek-ai/DeepSeek-V3'),
  ('meta-llama/llama-3.3-70b', 'featherless', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('meta-llama/llama-3.1-70b', 'featherless', 'meta-llama/Meta-Llama-3.1-70B-Instruct')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- together ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('meta-llama/llama-3.3-70b', 'together', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('meta-llama/llama-3.1-70b', 'together', 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo'),
  ('deepseek-ai/deepseek-v3', 'together', 'deepseek-ai/DeepSeek-V3')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- huggingface ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('meta-llama/llama-3.3-70b', 'huggingface', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('meta-llama/llama-3.3-70b-instruct', 'huggingface', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('meta-llama/llama-3.1-70b', 'huggingface', 'meta-llama/Meta-Llama-3.1-70B-Instruct'),
  ('meta-llama/llama-3.1-70b-instruct', 'huggingface', 'meta-llama/Meta-Llama-3.1-70B-Instruct'),
  ('meta-llama/llama-3.1-8b', 'huggingface', 'meta-llama/Meta-Llama-3.1-8B-Instruct'),
  ('meta-llama/llama-3.1-8b-instruct', 'huggingface', 'meta-llama/Meta-Llama-3.1-8B-Instruct'),
  ('deepseek-ai/deepseek-v3', 'huggingface', 'deepseek-ai/DeepSeek-V3'),
  ('deepseek-ai/deepseek-r1', 'huggingface', 'deepseek-ai/DeepSeek-R1'),
  ('qwen/qwen-2.5-72b', 'huggingface', 'Qwen/Qwen2.5-72B-Instruct'),
  ('qwen/qwen-2.5-72b-instruct', 'huggingface', 'Qwen/Qwen2.5-72B-Instruct'),
  ('qwen/qwen-2.5-7b', 'huggingface', 'Qwen/Qwen2.5-7B-Instruct'),
  ('qwen/qwen-2.5-7b-instruct', 'huggingface', 'Qwen/Qwen2.5-7B-Instruct'),
  ('mistralai/mistral-7b', 'huggingface', 'mistralai/Mistral-7B-Instruct-v0.3'),
  ('mistralai/mistral-7b-instruct', 'huggingface', 'mistralai/Mistral-7B-Instruct-v0.3'),
  ('mistralai/mixtral-8x7b', 'huggingface', 'mistralai/Mixtral-8x7B-Instruct-v0.1'),
  ('mistralai/mixtral-8x7b-instruct', 'huggingface', 'mistralai/Mixtral-8x7B-Instruct-v0.1'),
  ('microsoft/phi-3', 'huggingface', 'microsoft/Phi-3-medium-4k-instruct'),
  ('microsoft/phi-3-medium', 'huggingface', 'microsoft/Phi-3-medium-4k-instruct')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- hug (alias for huggingface) ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('meta-llama/llama-3.3-70b', 'hug', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('meta-llama/llama-3.3-70b-instruct', 'hug', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('meta-llama/llama-3.1-70b', 'hug', 'meta-llama/Meta-Llama-3.1-70B-Instruct'),
  ('meta-llama/llama-3.1-70b-instruct', 'hug', 'meta-llama/Meta-Llama-3.1-70B-Instruct'),
  ('meta-llama/llama-3.1-8b', 'hug', 'meta-llama/Meta-Llama-3.1-8B-Instruct'),
  ('meta-llama/llama-3.1-8b-instruct', 'hug', 'meta-llama/Meta-Llama-3.1-8B-Instruct'),
  ('deepseek-ai/deepseek-v3', 'hug', 'deepseek-ai/DeepSeek-V3'),
  ('deepseek-ai/deepseek-r1', 'hug', 'deepseek-ai/DeepSeek-R1'),
  ('qwen/qwen-2.5-72b', 'hug', 'Qwen/Qwen2.5-72B-Instruct'),
  ('qwen/qwen-2.5-72b-instruct', 'hug', 'Qwen/Qwen2.5-72B-Instruct'),
  ('qwen/qwen-2.5-7b', 'hug', 'Qwen/Qwen2.5-7B-Instruct'),
  ('qwen/qwen-2.5-7b-instruct', 'hug', 'Qwen/Qwen2.5-7B-Instruct'),
  ('mistralai/mistral-7b', 'hug', 'mistralai/Mistral-7B-Instruct-v0.3'),
  ('mistralai/mistral-7b-instruct', 'hug', 'mistralai/Mistral-7B-Instruct-v0.3'),
  ('mistralai/mixtral-8x7b', 'hug', 'mistralai/Mixtral-8x7B-Instruct-v0.1'),
  ('mistralai/mixtral-8x7b-instruct', 'hug', 'mistralai/Mixtral-8x7B-Instruct-v0.1'),
  ('microsoft/phi-3', 'hug', 'microsoft/Phi-3-medium-4k-instruct'),
  ('microsoft/phi-3-medium', 'hug', 'microsoft/Phi-3-medium-4k-instruct')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- groq ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('llama-3.3-70b-versatile', 'groq', 'llama-3.3-70b-versatile'),
  ('llama-3.1-70b-versatile', 'groq', 'llama-3.1-70b-versatile'),
  ('llama-3.1-8b-instant', 'groq', 'llama-3.1-8b-instant'),
  ('llama3-70b-8192', 'groq', 'llama3-70b-8192'),
  ('llama3-8b-8192', 'groq', 'llama3-8b-8192'),
  ('gemma2-9b-it', 'groq', 'gemma2-9b-it'),
  ('groq/llama-3.3-70b-versatile', 'groq', 'llama-3.3-70b-versatile'),
  ('groq/llama-3.1-70b-versatile', 'groq', 'llama-3.1-70b-versatile'),
  ('groq/llama-3.1-8b-instant', 'groq', 'llama-3.1-8b-instant'),
  ('groq/gemma2-9b-it', 'groq', 'gemma2-9b-it')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- google-vertex ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('gemini-3-flash', 'google-vertex', 'gemini-3-flash-preview'),
  ('gemini-3-flash-preview', 'google-vertex', 'gemini-3-flash-preview'),
  ('google/gemini-3-flash', 'google-vertex', 'gemini-3-flash-preview'),
  ('google/gemini-3-flash-preview', 'google-vertex', 'gemini-3-flash-preview'),
  ('@google/models/gemini-3-flash', 'google-vertex', 'gemini-3-flash-preview'),
  ('@google/models/gemini-3-flash-preview', 'google-vertex', 'gemini-3-flash-preview'),
  ('gemini-2.5-flash-lite', 'google-vertex', 'gemini-2.5-flash-lite'),
  ('google/gemini-2.5-flash-lite', 'google-vertex', 'gemini-2.5-flash-lite'),
  ('@google/models/gemini-2.5-flash-lite', 'google-vertex', 'gemini-2.5-flash-lite'),
  ('gemini-2.5-flash-lite-preview-09-2025', 'google-vertex', 'gemini-2.5-flash-lite-preview-09-2025'),
  ('google/gemini-2.5-flash-lite-preview-09-2025', 'google-vertex', 'gemini-2.5-flash-lite-preview-09-2025'),
  ('@google/models/gemini-2.5-flash-lite-preview-09-2025', 'google-vertex', 'gemini-2.5-flash-lite-preview-09-2025'),
  ('gemini-2.5-flash-lite-preview-06-17', 'google-vertex', 'gemini-2.5-flash-lite-preview-06-17'),
  ('google/gemini-2.5-flash-lite-preview-06-17', 'google-vertex', 'gemini-2.5-flash-lite-preview-06-17'),
  ('gemini-2.5-flash', 'google-vertex', 'gemini-2.5-flash'),
  ('google/gemini-2.5-flash', 'google-vertex', 'gemini-2.5-flash'),
  ('@google/models/gemini-2.5-flash', 'google-vertex', 'gemini-2.5-flash'),
  ('gemini-2.5-flash-preview-09-2025', 'google-vertex', 'gemini-2.5-flash-preview-09-2025'),
  ('gemini-2.5-flash-preview', 'google-vertex', 'gemini-2.5-flash-preview-09-2025'),
  ('google/gemini-2.5-flash-preview-09-2025', 'google-vertex', 'gemini-2.5-flash-preview-09-2025'),
  ('@google/models/gemini-2.5-flash-preview-09-2025', 'google-vertex', 'gemini-2.5-flash-preview-09-2025'),
  ('google/gemini-2.5-flash-image', 'google-vertex', 'gemini-2.5-flash-image'),
  ('gemini-2.5-flash-image', 'google-vertex', 'gemini-2.5-flash-image'),
  ('@google/models/gemini-2.5-flash-image', 'google-vertex', 'gemini-2.5-flash-image'),
  ('gemini-2.5-pro', 'google-vertex', 'gemini-2.5-pro'),
  ('google/gemini-2.5-pro', 'google-vertex', 'gemini-2.5-pro'),
  ('@google/models/gemini-2.5-pro', 'google-vertex', 'gemini-2.5-pro'),
  ('gemini-2.5-pro-preview-09-2025', 'google-vertex', 'gemini-2.5-pro-preview-09-2025'),
  ('google/gemini-2.5-pro-preview-09-2025', 'google-vertex', 'gemini-2.5-pro-preview-09-2025'),
  ('@google/models/gemini-2.5-pro-preview-09-2025', 'google-vertex', 'gemini-2.5-pro-preview-09-2025'),
  ('gemini-2.5-pro-preview', 'google-vertex', 'gemini-2.5-pro-preview-09-2025'),
  ('google/gemini-2.5-pro-preview', 'google-vertex', 'gemini-2.5-pro-preview-09-2025'),
  ('gemini-2.5-pro-preview-05-06', 'google-vertex', 'gemini-2.5-pro-preview-05-06'),
  ('google/gemini-2.5-pro-preview-05-06', 'google-vertex', 'gemini-2.5-pro-preview-05-06'),
  ('gemini-2.0-flash', 'google-vertex', 'gemini-2.0-flash'),
  ('gemini-2.0-flash-thinking', 'google-vertex', 'gemini-2.0-flash-thinking'),
  ('gemini-2.0-flash-001', 'google-vertex', 'gemini-2.0-flash-001'),
  ('gemini-2.0-flash-lite-001', 'google-vertex', 'gemini-2.0-flash-lite-001'),
  ('gemini-2.0-flash-exp', 'google-vertex', 'gemini-2.0-flash-exp'),
  ('google/gemini-2.0-flash', 'google-vertex', 'gemini-2.0-flash'),
  ('google/gemini-2.0-flash-001', 'google-vertex', 'gemini-2.0-flash-001'),
  ('google/gemini-2.0-flash-lite-001', 'google-vertex', 'gemini-2.0-flash-lite-001'),
  ('google/gemini-2.0-flash-exp', 'google-vertex', 'gemini-2.0-flash-exp'),
  ('@google/models/gemini-2.0-flash', 'google-vertex', 'gemini-2.0-flash'),
  ('gemini-2.0-pro', 'google-vertex', 'gemini-2.0-pro'),
  ('gemini-2.0-pro-001', 'google-vertex', 'gemini-2.0-pro-001'),
  ('google/gemini-2.0-pro', 'google-vertex', 'gemini-2.0-pro'),
  ('@google/models/gemini-2.0-pro', 'google-vertex', 'gemini-2.0-pro'),
  -- Gemini 1.5 retired → redirect to current equivalents
  ('gemini-1.5-pro', 'google-vertex', 'gemini-2.5-flash'),
  ('gemini-1.5-flash', 'google-vertex', 'gemini-2.5-flash-lite'),
  ('gemini-1.5-flash-8b', 'google-vertex', 'gemini-2.5-flash-lite'),
  ('google/gemini-1.5-pro', 'google-vertex', 'gemini-2.5-flash'),
  ('google/gemini-1.5-flash', 'google-vertex', 'gemini-2.5-flash-lite'),
  ('google/gemini-1.5-flash-8b', 'google-vertex', 'gemini-2.5-flash-lite'),
  ('@google/models/gemini-1.5-pro', 'google-vertex', 'gemini-2.5-flash'),
  ('@google/models/gemini-1.5-flash', 'google-vertex', 'gemini-2.5-flash-lite'),
  -- Gemini 1.0 retired → redirect to gemini-2.0-flash
  ('gemini-1.0-pro', 'google-vertex', 'gemini-2.0-flash'),
  ('gemini-1.0-pro-vision', 'google-vertex', 'gemini-2.0-flash'),
  ('google/gemini-1.0-pro', 'google-vertex', 'gemini-2.0-flash'),
  ('@google/models/gemini-1.0-pro', 'google-vertex', 'gemini-2.0-flash'),
  ('gemini-2.0', 'google-vertex', 'gemini-2.0-flash'),
  ('gemini-1.5', 'google-vertex', 'gemini-2.5-flash'),
  -- Gemma models
  ('google/gemma-2-9b', 'google-vertex', 'gemma-2-9b-it'),
  ('google/gemma-2-9b-it', 'google-vertex', 'gemma-2-9b-it'),
  ('google/gemma-2-27b-it', 'google-vertex', 'gemma-2-27b-it'),
  ('google/gemma-3-4b-it', 'google-vertex', 'gemma-3-4b-it'),
  ('google/gemma-3-12b-it', 'google-vertex', 'gemma-3-12b-it'),
  ('google/gemma-3-27b-it', 'google-vertex', 'gemma-3-27b-it'),
  ('google/gemma-3n-e2b-it', 'google-vertex', 'gemma-3n-e2b-it'),
  ('google/gemma-3n-e4b-it', 'google-vertex', 'gemma-3n-e4b-it'),
  ('gemma-2-9b-it', 'google-vertex', 'gemma-2-9b-it'),
  ('gemma-2-27b-it', 'google-vertex', 'gemma-2-27b-it'),
  ('gemma-3-4b-it', 'google-vertex', 'gemma-3-4b-it'),
  ('gemma-3-12b-it', 'google-vertex', 'gemma-3-12b-it'),
  ('gemma-3-27b-it', 'google-vertex', 'gemma-3-27b-it'),
  ('gemma-3n-e2b-it', 'google-vertex', 'gemma-3n-e2b-it'),
  ('gemma-3n-e4b-it', 'google-vertex', 'gemma-3n-e4b-it')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- near ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('deepseek-ai/deepseek-v3', 'near', 'deepseek-ai/DeepSeek-V3.1'),
  ('deepseek-ai/deepseek-v3.1', 'near', 'deepseek-ai/DeepSeek-V3.1'),
  ('deepseek-v3', 'near', 'deepseek-ai/DeepSeek-V3.1'),
  ('deepseek-v3.1', 'near', 'deepseek-ai/DeepSeek-V3.1'),
  ('gpt-oss/gpt-oss-120b', 'near', 'openai/gpt-oss-120b'),
  ('gpt-oss-120b', 'near', 'openai/gpt-oss-120b'),
  ('qwen/qwen-2-72b', 'near', 'Qwen/Qwen3-30B-A3B-Instruct-2507'),
  ('qwen-2-72b', 'near', 'Qwen/Qwen3-30B-A3B-Instruct-2507'),
  ('qwen/qwen-3-30b', 'near', 'Qwen/Qwen3-30B-A3B-Instruct-2507'),
  ('qwen/qwen-3-30b-instruct', 'near', 'Qwen/Qwen3-30B-A3B-Instruct-2507'),
  ('qwen-3-30b', 'near', 'Qwen/Qwen3-30B-A3B-Instruct-2507'),
  ('qwen/qwen3-30b-a3b-instruct-2507', 'near', 'Qwen/Qwen3-30B-A3B-Instruct-2507'),
  ('qwen3-30b-a3b-instruct-2507', 'near', 'Qwen/Qwen3-30B-A3B-Instruct-2507'),
  ('qwen/qwen3-30b-a3b-thinking-2507', 'near', 'Qwen/Qwen3-30B-A3B-Thinking-2507'),
  ('qwen3-30b-a3b-thinking-2507', 'near', 'Qwen/Qwen3-30B-A3B-Thinking-2507'),
  ('zai-org/glm-4.6-fp8', 'near', 'zai-org/GLM-4.6'),
  ('zai-org/glm-4.6', 'near', 'zai-org/GLM-4.6'),
  ('glm-4.6-fp8', 'near', 'zai-org/GLM-4.6'),
  ('glm-4.6', 'near', 'zai-org/GLM-4.6')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- alpaca-network ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('deepseek-ai/deepseek-v3.1', 'alpaca-network', 'deepseek-v3-1'),
  ('deepseek-ai/deepseek-v3', 'alpaca-network', 'deepseek-v3-1'),
  ('deepseek/deepseek-v3.1', 'alpaca-network', 'deepseek-v3-1'),
  ('deepseek/deepseek-v3', 'alpaca-network', 'deepseek-v3-1'),
  ('deepseek-v3.1', 'alpaca-network', 'deepseek-v3-1'),
  ('deepseek-v3', 'alpaca-network', 'deepseek-v3-1'),
  ('deepseek-v3-1', 'alpaca-network', 'deepseek-v3-1')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- alibaba-cloud ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('qwen/qwen-plus', 'alibaba-cloud', 'qwen-plus'),
  ('qwen/qwen-max', 'alibaba-cloud', 'qwen-max'),
  ('qwen/qwen-flash', 'alibaba-cloud', 'qwen-flash'),
  ('qwen-plus', 'alibaba-cloud', 'qwen-plus'),
  ('qwen-max', 'alibaba-cloud', 'qwen-max'),
  ('qwen-flash', 'alibaba-cloud', 'qwen-flash'),
  ('qwen/qwq-plus', 'alibaba-cloud', 'qwq-plus'),
  ('qwen/qwen-long', 'alibaba-cloud', 'qwen-long'),
  ('qwen/qwen-omni', 'alibaba-cloud', 'qwen-omni'),
  ('qwen/qwen-vl', 'alibaba-cloud', 'qwen-vl'),
  ('qwen/qwen-math', 'alibaba-cloud', 'qwen-math'),
  ('qwen/qwen-mt', 'alibaba-cloud', 'qwen-mt'),
  ('qwen/qvq', 'alibaba-cloud', 'qvq'),
  ('qwq-plus', 'alibaba-cloud', 'qwq-plus'),
  ('qwen-long', 'alibaba-cloud', 'qwen-long'),
  ('qwen-omni', 'alibaba-cloud', 'qwen-omni'),
  ('qwen-vl', 'alibaba-cloud', 'qwen-vl'),
  ('qwen-math', 'alibaba-cloud', 'qwen-math'),
  ('qwen-mt', 'alibaba-cloud', 'qwen-mt'),
  ('qvq', 'alibaba-cloud', 'qvq'),
  ('qwen/qwen-coder', 'alibaba-cloud', 'qwen-coder'),
  ('qwen-coder', 'alibaba-cloud', 'qwen-coder'),
  ('qwen/qwen-2.5-coder-32b-instruct', 'alibaba-cloud', 'qwen2.5-coder-32b-instruct'),
  ('qwen/qwen2.5-coder-32b-instruct', 'alibaba-cloud', 'qwen2.5-coder-32b-instruct'),
  ('qwen-2.5-coder-32b-instruct', 'alibaba-cloud', 'qwen2.5-coder-32b-instruct'),
  ('qwen2.5-coder-32b-instruct', 'alibaba-cloud', 'qwen2.5-coder-32b-instruct'),
  ('qwen/qwen-2.5-coder-32b', 'alibaba-cloud', 'qwen2.5-coder-32b-instruct'),
  ('qwen/qwen-2.5-coder-7b-instruct', 'alibaba-cloud', 'qwen2.5-coder-7b-instruct'),
  ('qwen/qwen2.5-coder-7b-instruct', 'alibaba-cloud', 'qwen2.5-coder-7b-instruct'),
  ('qwen-2.5-coder-7b-instruct', 'alibaba-cloud', 'qwen2.5-coder-7b-instruct'),
  ('qwen2.5-coder-7b-instruct', 'alibaba-cloud', 'qwen2.5-coder-7b-instruct'),
  ('qwen/qwen-2.5-coder-7b', 'alibaba-cloud', 'qwen2.5-coder-7b-instruct'),
  ('qwen/qwen-2.5-coder-14b-instruct', 'alibaba-cloud', 'qwen2.5-coder-14b-instruct'),
  ('qwen/qwen2.5-coder-14b-instruct', 'alibaba-cloud', 'qwen2.5-coder-14b-instruct'),
  ('qwen-2.5-coder-14b-instruct', 'alibaba-cloud', 'qwen2.5-coder-14b-instruct'),
  ('qwen2.5-coder-14b-instruct', 'alibaba-cloud', 'qwen2.5-coder-14b-instruct'),
  ('qwen/qwen-2.5-coder-14b', 'alibaba-cloud', 'qwen2.5-coder-14b-instruct'),
  ('qwen/qwq-32b-preview', 'alibaba-cloud', 'qwq-32b-preview'),
  ('qwq-32b-preview', 'alibaba-cloud', 'qwq-32b-preview'),
  ('qwen/qwen-3-30b-a3b-thinking', 'alibaba-cloud', 'qwen-3-30b-a3b-thinking'),
  ('qwen/qwen-3-80b-a3b-thinking', 'alibaba-cloud', 'qwen-3-80b-a3b-thinking'),
  ('qwen-3-30b-a3b-thinking', 'alibaba-cloud', 'qwen-3-30b-a3b-thinking'),
  ('qwen-3-80b-a3b-thinking', 'alibaba-cloud', 'qwen-3-80b-a3b-thinking'),
  ('qwen/qwen-3-30b', 'alibaba-cloud', 'qwen-3-30b-a3b-instruct'),
  ('qwen/qwen-3-80b', 'alibaba-cloud', 'qwen-3-80b-a3b-instruct'),
  ('qwen/qwen3-32b', 'alibaba-cloud', 'qwen-3-32b-a3b-instruct'),
  ('qwen3-30b', 'alibaba-cloud', 'qwen-3-30b-a3b-instruct'),
  ('qwen3-80b', 'alibaba-cloud', 'qwen-3-80b-a3b-instruct'),
  ('qwen3-32b', 'alibaba-cloud', 'qwen-3-32b-a3b-instruct'),
  ('qwen/qwen-2.5-72b', 'alibaba-cloud', 'qwen-2.5-72b-instruct'),
  ('qwen/qwen-2.5-7b', 'alibaba-cloud', 'qwen-2.5-7b-instruct'),
  ('qwen-2.5-72b', 'alibaba-cloud', 'qwen-2.5-72b-instruct'),
  ('qwen-2.5-7b', 'alibaba-cloud', 'qwen-2.5-7b-instruct'),
  ('qwen/qwen-2-72b', 'alibaba-cloud', 'qwen-2-72b-instruct'),
  ('qwen/qwen-2-7b', 'alibaba-cloud', 'qwen-2-7b-instruct'),
  ('qwen-2-72b', 'alibaba-cloud', 'qwen-2-72b-instruct'),
  ('qwen-2-7b', 'alibaba-cloud', 'qwen-2-7b-instruct'),
  ('qwen/qwen-1.5-72b', 'alibaba-cloud', 'qwen-1.5-72b-chat'),
  ('qwen/qwen-1.5-14b', 'alibaba-cloud', 'qwen-1.5-14b-chat'),
  ('qwen-1.5-72b', 'alibaba-cloud', 'qwen-1.5-72b-chat'),
  ('qwen-1.5-14b', 'alibaba-cloud', 'qwen-1.5-14b-chat'),
  ('qwen', 'alibaba-cloud', 'qwen-plus'),
  ('qwen-max-latest', 'alibaba-cloud', 'qwen-max'),
  ('qwen-plus-latest', 'alibaba-cloud', 'qwen-plus')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- clarifai ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('openai/gpt-4o', 'clarifai', 'openai/chat-completion/models/gpt-4o'),
  ('openai/gpt-4-turbo', 'clarifai', 'openai/chat-completion/models/gpt-4-turbo'),
  ('openai/gpt-4', 'clarifai', 'openai/chat-completion/models/gpt-4'),
  ('gpt-4o', 'clarifai', 'openai/chat-completion/models/gpt-4o'),
  ('gpt-4-turbo', 'clarifai', 'openai/chat-completion/models/gpt-4-turbo'),
  ('gpt-4', 'clarifai', 'openai/chat-completion/models/gpt-4'),
  ('gpt-oss-120b', 'clarifai', 'openai/chat-completion/models/gpt-oss-120b'),
  ('openai/gpt-oss-120b', 'clarifai', 'openai/chat-completion/models/gpt-oss-120b'),
  ('anthropic/claude-3-opus', 'clarifai', 'anthropic/completion/models/claude-3-opus'),
  ('anthropic/claude-3.5-sonnet', 'clarifai', 'anthropic/completion/models/claude-3-5-sonnet'),
  ('anthropic/claude-3-sonnet', 'clarifai', 'anthropic/completion/models/claude-3-sonnet'),
  ('claude-3-opus', 'clarifai', 'anthropic/completion/models/claude-3-opus'),
  ('claude-3.5-sonnet', 'clarifai', 'anthropic/completion/models/claude-3-5-sonnet'),
  ('claude-3-sonnet', 'clarifai', 'anthropic/completion/models/claude-3-sonnet'),
  ('meta-llama/llama-3.1-70b', 'clarifai', 'meta/llama-2/models/llama-3-1-70b-instruct'),
  ('meta-llama/llama-3-70b', 'clarifai', 'meta/llama-2/models/llama-3-70b-instruct'),
  ('llama-3.1-70b', 'clarifai', 'meta/llama-2/models/llama-3-1-70b-instruct'),
  ('llama-3-70b', 'clarifai', 'meta/llama-2/models/llama-3-70b-instruct'),
  ('mistralai/mistral-7b', 'clarifai', 'mistralai/completion/models/mistral-7b-instruct'),
  ('mistralai/mixtral-8x7b', 'clarifai', 'mistralai/completion/models/mixtral-8x7b-instruct'),
  ('mistral-7b', 'clarifai', 'mistralai/completion/models/mistral-7b-instruct'),
  ('mixtral-8x7b', 'clarifai', 'mistralai/completion/models/mixtral-8x7b-instruct')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- xai ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('grok-beta', 'xai', 'grok-3'),
  ('grok-vision-beta', 'xai', 'grok-3'),
  ('grok-2', 'xai', 'grok-3'),
  ('grok-2-1212', 'xai', 'grok-3'),
  ('grok-3', 'xai', 'grok-3'),
  ('xai/grok-beta', 'xai', 'grok-3'),
  ('xai/grok-vision-beta', 'xai', 'grok-3'),
  ('xai/grok-2', 'xai', 'grok-3'),
  ('xai/grok-2-1212', 'xai', 'grok-3'),
  ('xai/grok-3', 'xai', 'grok-3')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- cerebras ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('cerebras/llama-3.3-70b', 'cerebras', 'llama-3.3-70b'),
  ('cerebras/llama-3.3-70b-instruct', 'cerebras', 'llama-3.3-70b'),
  ('cerebras/llama-3.1-70b', 'cerebras', 'llama3.1-70b'),
  ('cerebras/llama-3.1-70b-instruct', 'cerebras', 'llama3.1-70b'),
  ('cerebras/llama-3.1-8b', 'cerebras', 'llama3.1-8b'),
  ('cerebras/llama-3.1-8b-instruct', 'cerebras', 'llama3.1-8b'),
  ('cerebras/llama-3.1-405b', 'cerebras', 'llama3.1-405b'),
  ('cerebras/qwen-3-32b', 'cerebras', 'qwen-3-32b'),
  ('cerebras/qwen-3-32b-instruct', 'cerebras', 'qwen-3-32b'),
  ('cerebras/qwen-3-235b', 'cerebras', 'qwen-3-235b-a22b-instruct-2507'),
  ('cerebras/qwen-3-235b-instruct', 'cerebras', 'qwen-3-235b-a22b-instruct-2507'),
  ('qwen-3-32b', 'cerebras', 'qwen-3-32b'),
  ('qwen3-32b', 'cerebras', 'qwen-3-32b'),
  ('qwen/qwen3-32b', 'cerebras', 'qwen-3-32b'),
  ('qwen/qwen-3-235b', 'cerebras', 'qwen-3-235b-a22b-instruct-2507'),
  ('qwen-3-235b', 'cerebras', 'qwen-3-235b-a22b-instruct-2507'),
  ('cerebras/zai-glm-4.6', 'cerebras', 'zai-glm-4.6'),
  ('zai-glm-4.6', 'cerebras', 'zai-glm-4.6'),
  ('zai/glm-4.6', 'cerebras', 'zai-glm-4.6'),
  ('llama-3.3-70b', 'cerebras', 'llama-3.3-70b'),
  ('llama3.1-70b', 'cerebras', 'llama3.1-70b'),
  ('llama3.1-8b', 'cerebras', 'llama3.1-8b'),
  ('llama3.1-405b', 'cerebras', 'llama3.1-405b')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- cloudflare-workers-ai ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('openai/gpt-oss-120b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-120b'),
  ('openai/gpt-oss-20b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-20b'),
  ('gpt-oss-120b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-120b'),
  ('gpt-oss-20b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-20b'),
  ('gpt-oss/gpt-120b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-120b'),
  ('gpt-oss/gpt-20b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-20b'),
  ('meta-llama/llama-4-scout-17b', 'cloudflare-workers-ai', '@cf/meta/llama-4-scout-17b-16e-instruct'),
  ('meta-llama/llama-4-scout-17b-16e-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-4-scout-17b-16e-instruct'),
  ('llama-4-scout', 'cloudflare-workers-ai', '@cf/meta/llama-4-scout-17b-16e-instruct'),
  ('meta-llama/llama-3.3-70b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.3-70b-instruct-fp8-fast'),
  ('meta-llama/llama-3.3-70b', 'cloudflare-workers-ai', '@cf/meta/llama-3.3-70b-instruct-fp8-fast'),
  ('llama-3.3-70b', 'cloudflare-workers-ai', '@cf/meta/llama-3.3-70b-instruct-fp8-fast'),
  ('meta-llama/llama-3.2-11b-vision-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-11b-vision-instruct'),
  ('meta-llama/llama-3.2-3b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-3b-instruct'),
  ('meta-llama/llama-3.2-1b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-1b-instruct'),
  ('llama-3.2-11b-vision', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-11b-vision-instruct'),
  ('llama-3.2-3b', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-3b-instruct'),
  ('llama-3.2-1b', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-1b-instruct'),
  ('meta-llama/llama-3.1-70b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-70b-instruct'),
  ('meta-llama/llama-3.1-70b', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-70b-instruct'),
  ('meta-llama/llama-3.1-8b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct'),
  ('meta-llama/llama-3.1-8b', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct'),
  ('llama-3.1-70b', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-70b-instruct'),
  ('llama-3.1-8b', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct'),
  ('llama-3.1-8b-fast', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct-fast'),
  ('meta-llama/llama-3-8b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3-8b-instruct'),
  ('meta-llama/llama-3-8b', 'cloudflare-workers-ai', '@cf/meta/llama-3-8b-instruct'),
  ('llama-3-8b', 'cloudflare-workers-ai', '@cf/meta/llama-3-8b-instruct'),
  ('meta-llama/llama-guard-3-8b', 'cloudflare-workers-ai', '@cf/meta/llama-guard-3-8b'),
  ('llama-guard-3', 'cloudflare-workers-ai', '@cf/meta/llama-guard-3-8b'),
  ('qwen/qwen3-30b', 'cloudflare-workers-ai', '@cf/qwen/qwen3-30b-a3b-fp8'),
  ('qwen/qwq-32b', 'cloudflare-workers-ai', '@cf/qwen/qwq-32b'),
  ('qwen/qwen2.5-coder-32b-instruct', 'cloudflare-workers-ai', '@cf/qwen/qwen2.5-coder-32b-instruct'),
  ('qwen/qwen2.5-coder-32b', 'cloudflare-workers-ai', '@cf/qwen/qwen2.5-coder-32b-instruct'),
  ('qwq-32b', 'cloudflare-workers-ai', '@cf/qwen/qwq-32b'),
  ('qwen3-30b', 'cloudflare-workers-ai', '@cf/qwen/qwen3-30b-a3b-fp8'),
  ('qwen2.5-coder-32b', 'cloudflare-workers-ai', '@cf/qwen/qwen2.5-coder-32b-instruct'),
  ('google/gemma-3-12b-it', 'cloudflare-workers-ai', '@cf/google/gemma-3-12b-it'),
  ('google/gemma-7b-it', 'cloudflare-workers-ai', '@cf/google/gemma-7b-it'),
  ('google/gemma-2b-it', 'cloudflare-workers-ai', '@cf/google/gemma-2b-it-lora'),
  ('gemma-3-12b', 'cloudflare-workers-ai', '@cf/google/gemma-3-12b-it'),
  ('gemma-7b', 'cloudflare-workers-ai', '@cf/google/gemma-7b-it'),
  ('gemma-2b', 'cloudflare-workers-ai', '@cf/google/gemma-2b-it-lora'),
  ('mistralai/mistral-small-3.1-24b-instruct', 'cloudflare-workers-ai', '@cf/mistral/mistral-small-3.1-24b-instruct'),
  ('mistralai/mistral-7b-instruct-v0.2', 'cloudflare-workers-ai', '@cf/mistralai/mistral-7b-instruct-v0.2'),
  ('mistralai/mistral-7b-instruct-v0.1', 'cloudflare-workers-ai', '@cf/mistralai/mistral-7b-instruct-v0.1'),
  ('mistral-small-3.1-24b', 'cloudflare-workers-ai', '@cf/mistral/mistral-small-3.1-24b-instruct'),
  ('mistral-7b-instruct', 'cloudflare-workers-ai', '@cf/mistralai/mistral-7b-instruct-v0.2'),
  ('mistral-7b', 'cloudflare-workers-ai', '@cf/mistralai/mistral-7b-instruct-v0.2'),
  ('deepseek-ai/deepseek-r1-distill-qwen-32b', 'cloudflare-workers-ai', '@cf/deepseek/deepseek-r1-distill-qwen-32b'),
  ('deepseek-r1-distill-qwen-32b', 'cloudflare-workers-ai', '@cf/deepseek/deepseek-r1-distill-qwen-32b'),
  ('deepseek-r1-distill', 'cloudflare-workers-ai', '@cf/deepseek/deepseek-r1-distill-qwen-32b'),
  ('ibm/granite-4.0-h-micro', 'cloudflare-workers-ai', '@cf/ibm/granite-4.0-h-micro'),
  ('granite-4.0-micro', 'cloudflare-workers-ai', '@cf/ibm/granite-4.0-h-micro'),
  ('aisingapore/gemma-sea-lion-v4-27b-it', 'cloudflare-workers-ai', '@cf/aisingapore/gemma-sea-lion-v4-27b-it'),
  ('sea-lion-27b', 'cloudflare-workers-ai', '@cf/aisingapore/gemma-sea-lion-v4-27b-it'),
  ('nousresearch/hermes-2-pro-mistral-7b', 'cloudflare-workers-ai', '@cf/nousresearch/hermes-2-pro-mistral-7b'),
  ('hermes-2-pro', 'cloudflare-workers-ai', '@cf/nousresearch/hermes-2-pro-mistral-7b'),
  ('microsoft/phi-2', 'cloudflare-workers-ai', '@cf/microsoft/phi-2'),
  ('phi-2', 'cloudflare-workers-ai', '@cf/microsoft/phi-2'),
  -- Direct @cf/ passthrough entries
  ('@cf/openai/gpt-oss-120b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-120b'),
  ('@cf/openai/gpt-oss-20b', 'cloudflare-workers-ai', '@cf/openai/gpt-oss-20b'),
  ('@cf/meta/llama-4-scout-17b-16e-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-4-scout-17b-16e-instruct'),
  ('@cf/meta/llama-3.3-70b-instruct-fp8-fast', 'cloudflare-workers-ai', '@cf/meta/llama-3.3-70b-instruct-fp8-fast'),
  ('@cf/meta/llama-3.2-11b-vision-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-11b-vision-instruct'),
  ('@cf/meta/llama-3.2-3b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-3b-instruct'),
  ('@cf/meta/llama-3.2-1b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.2-1b-instruct'),
  ('@cf/meta/llama-3.1-70b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-70b-instruct'),
  ('@cf/meta/llama-3.1-8b-instruct-fast', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct-fast'),
  ('@cf/meta/llama-3.1-8b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct'),
  ('@cf/meta/llama-3.1-8b-instruct-fp8', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct-fp8'),
  ('@cf/meta/llama-3.1-8b-instruct-awq', 'cloudflare-workers-ai', '@cf/meta/llama-3.1-8b-instruct-awq'),
  ('@cf/meta/meta-llama-3-8b-instruct', 'cloudflare-workers-ai', '@cf/meta/meta-llama-3-8b-instruct'),
  ('@cf/meta/llama-3-8b-instruct', 'cloudflare-workers-ai', '@cf/meta/llama-3-8b-instruct'),
  ('@cf/meta/llama-3-8b-instruct-awq', 'cloudflare-workers-ai', '@cf/meta/llama-3-8b-instruct-awq'),
  ('@cf/meta/llama-guard-3-8b', 'cloudflare-workers-ai', '@cf/meta/llama-guard-3-8b'),
  ('@cf/qwen/qwen3-30b-a3b-fp8', 'cloudflare-workers-ai', '@cf/qwen/qwen3-30b-a3b-fp8'),
  ('@cf/qwen/qwq-32b', 'cloudflare-workers-ai', '@cf/qwen/qwq-32b'),
  ('@cf/qwen/qwen2.5-coder-32b-instruct', 'cloudflare-workers-ai', '@cf/qwen/qwen2.5-coder-32b-instruct'),
  ('@cf/google/gemma-3-12b-it', 'cloudflare-workers-ai', '@cf/google/gemma-3-12b-it'),
  ('@cf/google/gemma-7b-it', 'cloudflare-workers-ai', '@cf/google/gemma-7b-it'),
  ('@cf/google/gemma-7b-it-lora', 'cloudflare-workers-ai', '@cf/google/gemma-7b-it-lora'),
  ('@cf/google/gemma-2b-it-lora', 'cloudflare-workers-ai', '@cf/google/gemma-2b-it-lora'),
  ('@cf/mistral/mistral-small-3.1-24b-instruct', 'cloudflare-workers-ai', '@cf/mistral/mistral-small-3.1-24b-instruct'),
  ('@cf/mistralai/mistral-7b-instruct-v0.2', 'cloudflare-workers-ai', '@cf/mistralai/mistral-7b-instruct-v0.2'),
  ('@cf/mistralai/mistral-7b-instruct-v0.2-lora', 'cloudflare-workers-ai', '@cf/mistralai/mistral-7b-instruct-v0.2-lora'),
  ('@cf/mistralai/mistral-7b-instruct-v0.1', 'cloudflare-workers-ai', '@cf/mistralai/mistral-7b-instruct-v0.1'),
  ('@cf/deepseek/deepseek-r1-distill-qwen-32b', 'cloudflare-workers-ai', '@cf/deepseek/deepseek-r1-distill-qwen-32b'),
  ('@cf/ibm/granite-4.0-h-micro', 'cloudflare-workers-ai', '@cf/ibm/granite-4.0-h-micro'),
  ('@cf/aisingapore/gemma-sea-lion-v4-27b-it', 'cloudflare-workers-ai', '@cf/aisingapore/gemma-sea-lion-v4-27b-it'),
  ('@cf/nousresearch/hermes-2-pro-mistral-7b', 'cloudflare-workers-ai', '@cf/nousresearch/hermes-2-pro-mistral-7b'),
  ('@cf/microsoft/phi-2', 'cloudflare-workers-ai', '@cf/microsoft/phi-2')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- morpheus ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('morpheus/llama-3.1-8b', 'morpheus', 'llama-3.1-8b'),
  ('morpheus/llama-3.1-70b', 'morpheus', 'llama-3.1-70b'),
  ('morpheus/mistral-7b', 'morpheus', 'mistral-7b'),
  ('morpheus/deepseek-r1', 'morpheus', 'deepseek-r1'),
  ('llama-3.1-8b', 'morpheus', 'llama-3.1-8b'),
  ('llama-3.1-70b', 'morpheus', 'llama-3.1-70b'),
  ('mistral-7b', 'morpheus', 'mistral-7b'),
  ('deepseek-r1', 'morpheus', 'deepseek-r1')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- onerouter ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('onerouter/claude-3-5-sonnet', 'onerouter', 'claude-3-5-sonnet@20241022'),
  ('onerouter/gpt-4', 'onerouter', 'gpt-4@latest'),
  ('onerouter/gpt-4o', 'onerouter', 'gpt-4o@latest'),
  ('onerouter/gpt-3.5-turbo', 'onerouter', 'gpt-4o-mini@latest'),
  ('claude-3-5-sonnet@20241022', 'onerouter', 'claude-3-5-sonnet@20241022'),
  ('claude-3-5-sonnet@20240620', 'onerouter', 'claude-3-5-sonnet@20241022'),
  ('gpt-4@latest', 'onerouter', 'gpt-4@latest'),
  ('gpt-4o@latest', 'onerouter', 'gpt-4o@latest'),
  ('gpt-4o-mini@latest', 'onerouter', 'gpt-4o-mini@latest'),
  ('claude-3-5-sonnet', 'onerouter', 'claude-3-5-sonnet@20241022'),
  ('gpt-4', 'onerouter', 'gpt-4@latest'),
  ('gpt-4o', 'onerouter', 'gpt-4o@latest'),
  ('gpt-3.5-turbo', 'onerouter', 'gpt-4o-mini@latest'),
  ('gpt-3.5-turbo@latest', 'onerouter', 'gpt-4o-mini@latest')
ON CONFLICT (model_id, provider) DO NOTHING;

-- ---- simplismart ----
INSERT INTO model_provider_mappings (model_id, provider, provider_model_id) VALUES
  ('simplismart/llama-3.1-8b', 'simplismart', 'meta-llama/Meta-Llama-3.1-8B-Instruct'),
  ('simplismart/llama-3.1-70b', 'simplismart', 'meta-llama/Meta-Llama-3.1-70B-Instruct'),
  ('simplismart/llama-3.1-405b', 'simplismart', 'meta-llama/Meta-Llama-3.1-405B-Instruct'),
  ('llama-3.1-8b', 'simplismart', 'meta-llama/Meta-Llama-3.1-8B-Instruct'),
  ('llama-3.1-70b', 'simplismart', 'meta-llama/Meta-Llama-3.1-70B-Instruct'),
  ('llama-3.1-405b', 'simplismart', 'meta-llama/Meta-Llama-3.1-405B-Instruct'),
  ('simplismart/llama-3.3-70b', 'simplismart', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('llama-3.3-70b', 'simplismart', 'meta-llama/Llama-3.3-70B-Instruct'),
  ('simplismart/llama-4-maverick', 'simplismart', 'meta-llama/Llama-4-Maverick-17B-Instruct'),
  ('llama-4-maverick', 'simplismart', 'meta-llama/Llama-4-Maverick-17B-Instruct'),
  ('simplismart/deepseek-r1', 'simplismart', 'deepseek-ai/DeepSeek-R1'),
  ('simplismart/deepseek-v3', 'simplismart', 'deepseek-ai/DeepSeek-V3'),
  ('deepseek-r1', 'simplismart', 'deepseek-ai/DeepSeek-R1'),
  ('deepseek-v3', 'simplismart', 'deepseek-ai/DeepSeek-V3'),
  ('simplismart/gemma-3-1b', 'simplismart', 'google/gemma-3-1b-it'),
  ('simplismart/gemma-3-4b', 'simplismart', 'google/gemma-3-4b-it'),
  ('simplismart/gemma-3-27b', 'simplismart', 'google/gemma-3-27b-it'),
  ('gemma-3-1b', 'simplismart', 'google/gemma-3-1b-it'),
  ('gemma-3-4b', 'simplismart', 'google/gemma-3-4b-it'),
  ('gemma-3-27b', 'simplismart', 'google/gemma-3-27b-it'),
  ('simplismart/qwen-2.5-14b', 'simplismart', 'Qwen/Qwen2.5-14B-Instruct'),
  ('simplismart/qwen-2.5-32b', 'simplismart', 'Qwen/Qwen2.5-32B-Instruct'),
  ('qwen-2.5-14b', 'simplismart', 'Qwen/Qwen2.5-14B-Instruct'),
  ('qwen-2.5-32b', 'simplismart', 'Qwen/Qwen2.5-32B-Instruct'),
  ('simplismart/mixtral-8x7b', 'simplismart', 'mistralai/Mixtral-8x7B-Instruct-v0.1-FP8'),
  ('mixtral-8x7b', 'simplismart', 'mistralai/Mixtral-8x7B-Instruct-v0.1-FP8'),
  ('simplismart/devstral-small', 'simplismart', 'mistralai/Devstral-Small-2505'),
  ('devstral-small', 'simplismart', 'mistralai/Devstral-Small-2505')
ON CONFLICT (model_id, provider) DO NOTHING;
